# SPDX-License-Identifier: GPL-3.0-or-later
# End-to-end np_save5 test.
# Inputs: NP_SAVE5, MAKE_SAVE (make_synth_save5), ROM (Black/White, optional), SAV, WORK.
cmake_minimum_required(VERSION 3.19)

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
set(S "${WORK}/edit.sav")
file(COPY_FILE "${SAV}" "${S}")

function(run expect_rc out_var)
    execute_process(COMMAND "${NP_SAVE5}" ${ARGN}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL expect_rc)
        message(FATAL_ERROR "np_save5 ${ARGN}: exit ${rc} (want ${expect_rc})\nstdout:\n${out}\nstderr:\n${err}")
    endif()
    set(${out_var} "${out}" PARENT_SCOPE)
    set(${out_var}_err "${err}" PARENT_SCOPE)
endfunction()

function(expect_json json value)
    string(JSON got GET "${json}" ${ARGN})
    if(NOT got STREQUAL value)
        message(FATAL_ERROR "JSON ${ARGN}: got '${got}', want '${value}'")
    endif()
endfunction()

function(make out)
    execute_process(COMMAND "${MAKE_SAVE}" ${ARGN} "${out}" RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "make_synth_save5 ${ARGN} failed")
    endif()
endfunction()

# ---- dump without a ROM
run(0 j dump "${S}")
expect_json("${j}" "black" game)
expect_json("${j}" "ok" load_result)
expect_json("${j}" "backup" active)
expect_json("${j}" "ON" copies 0 valid)
expect_json("${j}" "5" copies 1 save_counter)
expect_json("${j}" "Hilbert" trainer name)
expect_json("${j}" "3000" trainer money)
expect_json("${j}" "3" trainer badges)
expect_json("${j}" "12:34:56" trainer play_time)
expect_json("${j}" "391" location map)
expect_json("${j}" "7" location x)
expect_json("${j}" "495" party 0 species)
expect_json("${j}" "SNIVY" party 0 nickname)
expect_json("${j}" "ON" party 0 checksum_ok)
expect_json("${j}" "506" boxes 0 mons 0 species)
expect_json("${j}" "BOX 1" boxes 0 name)
expect_json("${j}" "2" current_box)
expect_json("${j}" "4" bag items 0 item)
expect_json("${j}" "10" bag items 0 qty)
expect_json("${j}" "1" pokedex caught)
expect_json("${j}" "2" pokedex seen)
expect_json("${j}" "10" flags 0)
expect_json("${j}" "4660" vars 16400)
expect_json("${j}" "77" mystery_gift cards 0 id)
expect_json("${j}" "pokemon" mystery_gift cards 0 type_name)
expect_json("${j}" "Test Card" mystery_gift cards 0 title)
string(JSON nparty LENGTH "${j}" party)
if(NOT nparty EQUAL 2)
    message(FATAL_ERROR "party length ${nparty}")
endif()
run(0 v verify "${S}")
if(NOT v MATCHES "all checksums valid")
    message(FATAL_ERROR "verify: ${v}")
endif()

# ---- edits: in place (with .bak) and to -o
run(0 o set-money "${S}" 424242)
if(NOT EXISTS "${S}.bak")
    message(FATAL_ERROR "no backup written")
endif()
file(SHA256 "${S}.bak" h_bak)
file(SHA256 "${SAV}" h_orig)
if(NOT h_bak STREQUAL h_orig)
    message(FATAL_ERROR "backup differs from original")
endif()
run(0 o set-name "${S}" Hilda)
run(0 o set-ids "${S}" 111 222)
run(0 o set-badges "${S}" 255)
run(0 o set-item "${S}" medicine 2 28 9)
run(0 o set-dex "${S}" 25 caught)
run(0 o set-national-dex "${S}" 1)
run(0 o set-flag "${S}" 100 1)
run(0 o set-var "${S}" 0x4020 77)
run(0 o set-box-name "${S}" 3 Keepers)
run(0 o set-location "${S}" 252 8 0 9)
make("${WORK}/item.pgf" pgf 2 300)
run(0 o add-gift "${S}" "${WORK}/item.pgf")
run(0 o remove-gift "${S}" 1)
run(0 o set-money "${S}" 5 -o "${WORK}/out.sav")

run(0 j dump "${S}")
expect_json("${j}" "424242" trainer money)
expect_json("${j}" "Hilda" trainer name)
expect_json("${j}" "111" trainer tid)
expect_json("${j}" "8" trainer badges)
expect_json("${j}" "252" location map)
expect_json("${j}" "9" location z)
expect_json("${j}" "28" bag medicine 1 item)
expect_json("${j}" "9" bag medicine 1 qty)
expect_json("${j}" "Keepers" boxes 2 name)
expect_json("${j}" "2" pokedex caught)
expect_json("${j}" "ON" pokedex national)
expect_json("${j}" "77" vars 16416)
expect_json("${j}" "item" mystery_gift cards 0 type_name)
expect_json("${j}" "2" mystery_gift cards 0 slot)
expect_json("${j}" "300" mystery_gift received 1)
run(0 j dump "${WORK}/out.sav")
expect_json("${j}" "5" trainer money)
run(0 v verify "${S}")
if(NOT v MATCHES "all checksums valid")
    message(FATAL_ERROR "verify after edits: ${v}")
endif()

# ---- invalid values exit 2 and leave the file alone
file(SHA256 "${S}" h_before)
run(2 o set-money "${S}" 10000000)
run(2 o set-name "${S}" TooLongName)
run(2 o set-flag "${S}" 2912 1)
run(2 o set-var "${S}" 0x3FFF 1)
run(2 o set-item "${S}" key_items 1 442 2)
make("${WORK}/bad.pgf" pgf 9 5)
run(2 o add-gift "${S}" "${WORK}/bad.pgf")
file(SHA256 "${S}" h_after)
if(NOT h_before STREQUAL h_after)
    message(FATAL_ERROR "failed edit modified the save")
endif()

# ---- checksum failure: both copies of the trainer block corrupted -> exit 3
set(BAD "${WORK}/bad.sav")
make("${BAD}" black-corrupt)
run(3 o dump "${BAD}")
if(NOT o_err MATCHES "checksum failure" OR NOT o_err MATCHES "block 27 \\(trainer")
    message(FATAL_ERROR "missing checksum error report: ${o_err}")
endif()
run(3 o set-money "${BAD}" 5)
run(3 o verify "${BAD}")
message(STATUS "checksum failure reported: ${o_err}")

# ---- one copy corrupted: recovered from the other
set(REC "${WORK}/recover.sav")
make("${REC}" black-recover)
run(0 v verify "${REC}")
if(NOT v MATCHES "recovered" OR NOT v MATCHES "block 27 \\(trainer")
    message(FATAL_ERROR "verify of a recoverable save: ${v}")
endif()
run(0 j dump "${REC}")
expect_json("${j}" "recovered" load_result)
expect_json("${j}" "primary" active)
expect_json("${j}" "27" copies 1 bad_blocks 0)

# ---- White
make("${WORK}/white.sav" white)
run(0 j dump "${WORK}/white.sav")
expect_json("${j}" "white" game)

# ---- names, gamedata and add-mon from the ROM
if(EXISTS "${ROM}")
    run(0 j dump "${ROM}" "${S}")
    expect_json("${j}" "Snivy" party 0 species_name)
    expect_json("${j}" "Nuvema Town" location name)
    expect_json("${j}" "Tackle" party 0 moves 0 name)
    expect_json("${j}" "Poké Ball" party 0 ball name)
    expect_json("${j}" "Lillipup" boxes 0 mons 0 species_name)
    run(0 g gamedata "${ROM}")
    string(JSON ntypes LENGTH "${g}" type_chart)
    if(NOT ntypes EQUAL 17)
        message(FATAL_ERROR "type chart has ${ntypes} rows")
    endif()
    expect_json("${g}" "20" type_chart 9 11)
    run(0 o add-mon "${S}" "${ROM}" 498 5 33 45)
    run(0 j dump "${ROM}" "${S}")
    expect_json("${j}" "Tepig" party 2 species_name)
    expect_json("${j}" "5" party 2 level)
    expect_json("${j}" "Growl" party 2 moves 1 name)
    expect_json("${j}" "ON" party 2 checksum_ok)
    run(0 v verify "${S}")
    message(STATUS "ROM names, gamedata and add-mon OK")
else()
    message(STATUS "Black/White ROM not found at '${ROM}'; name checks skipped")
endif()
