# SPDX-License-Identifier: GPL-3.0-or-later
# End-to-end np_save4 test.
# Inputs: NP_SAVE4, MAKE_SAVE (make_synth_save), ROM, SAV, WORK.
cmake_minimum_required(VERSION 3.19)

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
set(S "${WORK}/edit.sav")
file(COPY_FILE "${SAV}" "${S}")

function(run expect_rc out_var)
    execute_process(COMMAND "${NP_SAVE4}" ${ARGN}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL expect_rc)
        message(FATAL_ERROR "np_save4 ${ARGN}: exit ${rc} (want ${expect_rc})\nstdout:\n${out}\nstderr:\n${err}")
    endif()
    set(${out_var} "${out}" PARENT_SCOPE)
    set(${out_var}_err "${err}" PARENT_SCOPE)
endfunction()

function(expect_json json value)
    string(JSON got GET "${json}" ${ARGN})
    if(NOT got STREQUAL value)
        message(FATAL_ERROR "JSON ${ARGN}: got '${got}', want '${value}'")
    endif()
endfunction()

# ---- dump with names from the ROM
if(EXISTS "${ROM}")
    run(0 j dump "${ROM}" "${S}")
    expect_json("${j}" "CPUE" rom gamecode)
    expect_json("${j}" "TURTWIG" party 0 species_name)
    expect_json("${j}" "Tackle" party 0 moves 0 name)
    expect_json("${j}" "Twinleaf Town" party 0 met_location name)
    expect_json("${j}" "Poké Ball" party 0 ball name)
    expect_json("${j}" "Overgrow" party 0 ability name)
    expect_json("${j}" "BULBASAUR" party 1 species_name)
    expect_json("${j}" "Vine Whip" party 1 moves 0 name)
    expect_json("${j}" "STARLY" boxes 0 mons 0 species_name)
    expect_json("${j}" "Potion" bag items 0 name)
    file(WRITE "${WORK}/dump_with_rom.json" "${j}")
    message(STATUS "dump with ROM names OK")
else()
    message(STATUS "ROM not found at ${ROM}; name checks skipped")
endif()

# ---- dump without a ROM
run(0 j dump "${S}")
expect_json("${j}" "Pt" game)
expect_json("${j}" "Lucas" trainer name)
expect_json("${j}" "3000" trainer money)
expect_json("${j}" "387" party 0 species)
expect_json("${j}" "TURTWIG" party 0 nickname)
expect_json("${j}" "Box 1" boxes 0 name)
string(JSON nparty LENGTH "${j}" party)
if(NOT nparty EQUAL 2)
    message(FATAL_ERROR "party length ${nparty}")
endif()

# ---- edits: in place (with .bak) and to -o
run(0 o set-money "${S}" 424242)
if(NOT EXISTS "${S}.bak")
    message(FATAL_ERROR "no backup written")
endif()
file(SHA256 "${S}.bak" h_bak)
file(SHA256 "${SAV}" h_orig)
if(NOT h_bak STREQUAL h_orig)
    message(FATAL_ERROR "backup differs from original")
endif()
run(0 o set-name "${S}" Barry)
run(0 o set-badges "${S}" 255)
run(0 o set-item "${S}" medicine 1 28 9)
run(0 o set-dex "${S}" 25 caught)
run(0 o set-flag "${S}" 100 1)
run(0 o set-var "${S}" 0x4020 77)
run(0 o set-box-name "${S}" 3 Keepers)
run(0 o set-coins "${S}" 50000 -o "${WORK}/out.sav")

run(0 j dump "${S}")
expect_json("${j}" "424242" trainer money)
expect_json("${j}" "Barry" trainer name)
expect_json("${j}" "8" trainer badges)
expect_json("${j}" "28" bag medicine 0 item)
expect_json("${j}" "9" bag medicine 0 qty)
expect_json("${j}" "Keepers" boxes 2 name)
expect_json("${j}" "2" pokedex caught)
expect_json("${j}" "100" trainer coins)
run(0 j dump "${WORK}/out.sav")
expect_json("${j}" "50000" trainer coins)
run(0 v verify "${S}")

if(EXISTS "${ROM}")
    run(0 j dump "${ROM}" "${S}")
    expect_json("${j}" "Revive" bag medicine 0 name)
    expect_json("${j}" "TURTWIG" party 0 species_name)
    file(WRITE "${WORK}/dump_after_edits.json" "${j}")
endif()

# ---- invalid values exit 2 and leave the file alone
file(SHA256 "${S}" h_before)
run(2 o set-money "${S}" 1000000)
run(2 o set-name "${S}" ThisNameIsTooLong)
run(2 o set-flag "${S}" NOT_A_FLAG 1)
file(SHA256 "${S}" h_after)
if(NOT h_before STREQUAL h_after)
    message(FATAL_ERROR "failed edit modified the save")
endif()

# ---- checksum failure: both copies of the general block corrupted -> exit 3
set(BAD "${WORK}/bad.sav")
execute_process(COMMAND "${MAKE_SAVE}" pt-corrupt "${BAD}" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "make_synth_save pt-corrupt failed")
endif()
run(3 o dump "${BAD}")
if(NOT o_err MATCHES "checksum failure")
    message(FATAL_ERROR "missing checksum error message: ${o_err}")
endif()
run(3 o set-money "${BAD}" 5)
run(3 o verify "${BAD}")
message(STATUS "checksum failure reported: ${o_err}")

# ---- Diamond/Pearl: Mystery Gift and Pokedex flags through the CLI
function(make out)
    execute_process(COMMAND "${MAKE_SAVE}" ${ARGN} "${out}" RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "make_synth_save ${ARGN} failed")
    endif()
endfunction()
set(DP "${WORK}/dp.sav")
make("${DP}" dp)
make("${WORK}/member.pcd" card 8)
make("${WORK}/rotom.pcd" card 12)
run(0 j dump "${DP}")
expect_json("${j}" "DP" game)
expect_json("${j}" "OFF" mystery_gift unlocked)
run(0 o set-mystery-gift "${DP}" 1)
run(0 o set-dex-obtained "${DP}" 1)
run(0 o set-national-dex "${DP}" 1)
run(0 o add-gift "${DP}" "${WORK}/member.pcd")
file(SHA256 "${DP}" h_before)
run(2 o add-gift "${DP}" "${WORK}/rotom.pcd")
if(NOT o_err MATCHES "secret_key")
    message(FATAL_ERROR "missing unsupported-type message: ${o_err}")
endif()
file(SHA256 "${DP}" h_after)
if(NOT h_before STREQUAL h_after)
    message(FATAL_ERROR "refused gift modified the save")
endif()
run(0 j dump "${DP}")
expect_json("${j}" "ON" mystery_gift unlocked)
expect_json("${j}" "1" mystery_gift pgts)
expect_json("${j}" "member_card" mystery_gift cards 0 type_name)
expect_json("${j}" "42" mystery_gift cards 0 id)
expect_json("${j}" "ON" pokedex obtained)
expect_json("${j}" "ON" pokedex national)
expect_json("${j}" "ON" trainer national_dex)
run(0 v verify "${DP}")
run(0 o remove-gift "${DP}" 1)
run(0 j dump "${DP}")
expect_json("${j}" "0" mystery_gift pgts)
string(JSON ncards LENGTH "${j}" mystery_gift cards)
if(NOT ncards EQUAL 0)
    message(FATAL_ERROR "card not removed: ${ncards}")
endif()
# Platinum delivers the Secret Key.
run(0 o add-gift "${WORK}/out.sav" "${WORK}/rotom.pcd")
run(0 j dump "${WORK}/out.sav")
expect_json("${j}" "secret_key" mystery_gift cards 0 type_name)

# ---- HeartGold / SoulSilver: the HG/SS layout through every verb
function(expect_type json type)
    string(JSON got TYPE "${json}" ${ARGN})
    if(NOT got STREQUAL type)
        message(FATAL_ERROR "JSON ${ARGN}: type ${got}, want ${type}")
    endif()
endfunction()
set(HG "${WORK}/hg.sav")
set(SS "${WORK}/ss.sav")
make("${HG}" hg)
make("${SS}" ss)
make("${WORK}/pokemon.pcd" card 1)
make("${WORK}/walker.pcd" card 14)
run(0 j dump "${SS}")
expect_json("${j}" "soulsilver" game)
run(0 j dump "${HG}")
expect_json("${j}" "heartgold" game)
expect_json("${j}" "ok" load_result)
expect_json("${j}" "Lucas" trainer name)
expect_json("${j}" "3000" trainer money)
expect_json("${j}" "3" trainer badges)
expect_json("${j}" "2" trainer kanto_badges)
expect_json("${j}" "3" trainer kanto_badge_mask)
expect_json("${j}" "100" trainer coins)
expect_json("${j}" "387" party 0 species)
expect_json("${j}" "18" party 1 ball id)
expect_json("${j}" "Box 18" boxes 17 name)
expect_json("${j}" "396" boxes 0 mons 0 species)
expect_json("${j}" "4" bag balls 0 item)
expect_json("${j}" "10" flags 0)
expect_json("${j}" "4660" vars 16400)
expect_json("${j}" "1" pokedex caught)
expect_json("${j}" "OFF" pokedex obtained)
expect_json("${j}" "OFF" mystery_gift unlocked)
expect_type("${j}" NULL poketch)
expect_type("${j}" NULL hall_of_fame)
expect_type("${j}" ARRAY daycare mons) # HG/SS Daycare at general 0x15FC (np_save4.c); this synthetic save's bytes there are filler
expect_type("${j}" BOOLEAN daycare egg_waiting)
expect_type("${j}" NULL roamers)
expect_type("${j}" NULL poffins)
expect_type("${j}" NULL trophy_garden)
expect_type("${j}" NULL underground)
expect_type("${j}" NULL game_records)
run(0 v verify "${HG}")
if(NOT v MATCHES "heartgold save, all checksums valid")
    message(FATAL_ERROR "verify: ${v}")
endif()

run(0 o set-money "${HG}" 999999)
run(0 o set-coins "${HG}" 50000)
run(0 o set-name "${HG}" Ethan)
run(0 o set-ids "${HG}" 1 2)
run(0 o set-badges "${HG}" 255)
run(0 o set-kanto-badges "${HG}" 129)
run(0 o set-item "${HG}" balls 24 494 3)
run(0 o set-item "${HG}" tms_hms 101 420 1)
run(0 o set-flag "${HG}" 2911 1)
run(0 o set-var "${HG}" 0x416F 5)
run(0 o set-dex "${HG}" 152 caught)
run(0 o set-dex-obtained "${HG}" 1)
run(0 o set-national-dex "${HG}" 1)
run(0 o set-mystery-gift "${HG}" 1)
run(0 o set-box-name "${HG}" 18 Johto)
run(0 o add-gift "${HG}" "${WORK}/pokemon.pcd")
run(0 o add-gift "${HG}" "${WORK}/walker.pcd")
file(SHA256 "${HG}" h_before)
run(2 o add-gift "${HG}" "${WORK}/member.pcd")
if(NOT o_err MATCHES "member_card.*heartgold")
    message(FATAL_ERROR "missing unsupported-type message: ${o_err}")
endif()
run(2 o set-flag "${HG}" FLAG_UNK_000 1)
run(2 o set-var "${HG}" 0x4170 1)
run(2 o set-item "${HG}" balls 25 4 1)
file(SHA256 "${HG}" h_after)
if(NOT h_before STREQUAL h_after)
    message(FATAL_ERROR "refused HG/SS edit modified the save")
endif()
run(0 v verify "${HG}")
run(0 j dump "${HG}")
expect_json("${j}" "999999" trainer money)
expect_json("${j}" "50000" trainer coins)
expect_json("${j}" "Ethan" trainer name)
expect_json("${j}" "1" trainer tid)
expect_json("${j}" "2" trainer sid)
expect_json("${j}" "8" trainer badges)
expect_json("${j}" "2" trainer kanto_badges)
expect_json("${j}" "129" trainer kanto_badge_mask)
expect_json("${j}" "494" bag balls 1 item)
expect_json("${j}" "420" bag tms_hms 0 item)
expect_json("${j}" "2911" flags 1)
expect_json("${j}" "5" vars 16751)
expect_json("${j}" "2" pokedex caught)
expect_json("${j}" "ON" pokedex obtained)
expect_json("${j}" "ON" pokedex national)
expect_json("${j}" "ON" trainer national_dex)
expect_json("${j}" "ON" mystery_gift unlocked)
expect_json("${j}" "pokemon" mystery_gift cards 0 type_name)
expect_json("${j}" "pokewalker_course" mystery_gift cards 1 type_name)
expect_json("${j}" "2" mystery_gift pgts)
expect_json("${j}" "Johto" boxes 17 name)
run(0 o remove-gift "${HG}" 1)
run(0 j dump "${HG}")
expect_json("${j}" "1" mystery_gift pgts)
# Kanto badges do not exist in Platinum.
run(2 o set-kanto-badges "${WORK}/out.sav" 1)
run(0 j dump "${WORK}/out.sav")
expect_type("${j}" NULL trainer kanto_badges)
# Platinum's pockets are smaller.
run(2 o set-item "${WORK}/out.sav" balls 16 4 1)

# ---- HG/SS checksum failure -> exit 3
make("${WORK}/hg_bad.sav" hg-corrupt)
run(3 o dump "${WORK}/hg_bad.sav")
if(NOT o_err MATCHES "checksum failure" OR NOT o_err MATCHES "heartgold")
    message(FATAL_ERROR "missing HG/SS checksum error: ${o_err}")
endif()
run(3 o verify "${WORK}/hg_bad.sav")

# ---- add-mon with an HG/SS ROM (names and base data from the ROM)
if(EXISTS "${HGSS_ROM}")
    run(0 o add-mon "${SS}" "${HGSS_ROM}" 152 5 33 45)
    run(0 j dump "${HGSS_ROM}" "${SS}")
    expect_json("${j}" "CHIKORITA" party 2 species_name)
    expect_json("${j}" "Poké Ball" party 2 ball name)
    expect_json("${j}" "Level Ball" party 1 ball name)
    run(0 o set-move "${SS}" "${HGSS_ROM}" 2 1 22)  # Vine Whip into the added Chikorita's second move
    run(0 j dump "${HGSS_ROM}" "${SS}")
    expect_json("${j}" "22" party 2 moves 1 id)
    expect_json("${j}" "15" party 2 moves 1 pp)  # Vine Whip's base PP in Gen 4
    run(2 o set-move "${SS}" "${HGSS_ROM}" 5 0 33)  # no Pokemon in slot 5: invalid value
    run(0 o set-level "${SS}" "${HGSS_ROM}" 2 30)  # the Chikorita from 5 to 30
    run(0 j dump "${HGSS_ROM}" "${SS}")
    expect_json("${j}" "30" party 2 level)
    expect_json("${j}" "21760" party 2 exp)  # Medium Slow at 30: 6/5 n^3 - 15 n^2 + 100 n - 140
    expect_json("${j}" "73" party 2 hp)  # (2*45 + IV 20) * 30/100 + 30 + 10, full
    expect_json("${j}" "22" party 2 moves 1 id)  # moves kept
    run(2 o set-level "${SS}" "${HGSS_ROM}" 5 30)  # no Pokemon in slot 5: invalid value
    run(0 o heal-party "${SS}" "${HGSS_ROM}")  # already full: HP, PP and status as they were
    run(0 j dump "${HGSS_ROM}" "${SS}")
    expect_json("${j}" "73" party 2 hp)
    expect_json("${j}" "15" party 2 moves 1 pp)  # Vine Whip's base PP, no PP Ups
    expect_json("${j}" "0" party 2 status)
    expect_json("${j}" "30" party 2 level)
    message(STATUS "HG/SS add-mon, set-move, set-level and heal-party with ROM OK")
else()
    message(STATUS "HG/SS ROM not found at '${HGSS_ROM}'; add-mon / name checks skipped")
endif()
message(STATUS "HG/SS CLI checks OK")
