/*
 * FS_StartOverlay, for a port whose overlays never leave memory.
 *
 * On hardware, loading an overlay reads its image out of the ROM into RAM and
 * then FS_StartOverlay runs the overlay's static initialisers, a list of
 * function addresses the SDK linker assigned inside the overlay's own text.
 * The compiled SDK version of that walk is faithful, and here faithful is
 * fatal: the overlay table comes from the real ROM, so the entries are DS
 * addresses and calling one jumps into guest RAM.
 *
 * That is not hypothetical. The first battle anyone reached on this port died
 * at an address the ROM link's own map names as battle_main.c's
 * NitroStaticInit with the Thumb bit set. Every overlay loaded before that
 * point has an empty list, which is why days of intro, overworld and menus
 * never tripped it.
 *
 * The correct model for C++-style statics is still to call nothing: those are
 * host globals the loader already ran. NitroStaticInit is different; it is a
 * regular function the overlay loader is supposed to call, and gcc never does.
 * Poketch apps use it to hand New and Exit to the system that just created
 * itself, and skipping it leaves currAppInit as stack garbage.
 *
 * pc/include/nitro/sinit.h records each unit's NitroStaticInit at process
 * start. This walks the ones whose source file belongs to the overlay that
 * just loaded. Overlays that register none still see an empty walk.
 *
 * FS_EndOverlay stays the SDK's: its destructor walk filters by the overlay's
 * guest address range, and no host destructor registers an address there.
 *
 * Reload resets host statics. On hardware the ROM copy is the reset; here the
 * statics are host globals, so the first StartOverlay snapshots the
 * CRT-initialised bytes and every later one copies that snapshot back. The
 * name list is generated from nm over each overlay's objects, and the
 * addresses come from the binary's own .symtab at runtime, because a generated
 * pointer table would move the very addresses it named. A host with no
 * .symtab (3DS, wasm) carries them in a table of the generator's, patched
 * into the finished image after the link; pc_sym.h answers the same way.
 */
#include <nitro/fs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "pc_overlay.h"
#include "pc_sym.h"

#if defined(__wasm__)
#include <pc_wasm.h>
#endif

extern void *malloc(size_t n);
extern void free(void *p);

#define PC_SINIT_MAX 128

struct pc_sinit_entry {
    const char *file;
    void (*fn)(void);
};

static struct pc_sinit_entry sSinit[PC_SINIT_MAX];
static int sSinitN;

void pc_sinit_record(const char *file, void (*fn)(void))
{
    if (sSinitN >= PC_SINIT_MAX) {
        fprintf(stderr, "pc_sinit: more than %d NitroStaticInit TUs\n",
                PC_SINIT_MAX);
        exit(2);
    }
    sSinit[sSinitN].file = file;
    sSinit[sSinitN].fn = fn;
    sSinitN++;
}

/*
 * overlay-map.txt names, turned into a path fragment that __FILE__ will
 * contain. Only TUs that actually define NitroStaticInit need to be here;
 * the rest of an overlay has nothing to run.
 */
static const struct {
    u32 overlay;
    const char *needle;
} sSinitNeedles[] = {
    /* Needles omit the .c suffix: the compile that produced the object is
       the stripped copy, named main.o.stripped.c, so "main.c" would miss. */
    { 26, "poketch/digital_watch/main" },
    { 27, "poketch/stopwatch/main" },
    { 28, "poketch/calculator/main" },
    { 29, "poketch/memo_pad/main" },
    { 30, "poketch/analog_watch/main" },
    { 31, "poketch/dot_artist/main" },
    { 32, "poketch/party_status/main" },
    { 33, "poketch/friendship_checker/main" },
    { 34, "poketch/dowsing_machine/main" },
    { 35, "poketch/counter/main" },
    { 36, "poketch/pedometer/main" },
    { 37, "poketch/backlight_toggle/main" },
    { 38, "poketch/unused/1/main" },
    { 39, "poketch/unused/2/main" },
    { 40, "poketch/daycare_checker/main" },
    { 41, "poketch/roulette/main" },
    { 42, "poketch/coin_toss/main" },
    { 43, "poketch/move_tester/main" },
    { 44, "poketch/matchup_checker/main" },
    { 45, "poketch/alarm_clock/main" },
    { 46, "poketch/kitchen_timer/main" },
    { 47, "poketch/marking_map/main" },
    { 48, "poketch/berry_searcher/main" },
    { 49, "poketch/color_changer/main" },
    { 50, "poketch/calendar/main" },
    { 51, "poketch/unused/3/main" },
    { 52, "poketch/link_searcher/main" },
    { 53, "poketch/trainer_counter/main" },
    { 54, "poketch/pokemon_history/main" },
    { 55, "poketch/unused/4/main" },
};

/*
 * Generated by pc/gen_overlay_statics.py. Names and object-nm sizes only;
 * see the file header for why the addresses are not in here.
 */
struct pc_ov_static_desc {
    unsigned overlay;
    const char *name;
    unsigned size;
};

extern const struct pc_ov_static_desc pc_ov_static_desc[];
extern const int pc_ov_static_desc_n;

#define PC_OV_SLOT_MAX 256

struct pc_ov_slot {
    unsigned overlay;
    void *addr;
    unsigned size;
    void *snap;
};

static struct pc_ov_slot sOvSlots[PC_OV_SLOT_MAX];
static int sOvSlotN;
static int sOvResolved;
static int sOvNoSymtab;
static unsigned sOvLoads[128];
static int sOvWarnedNoSym;

/*
 * Running totals, for a host that cannot read PC_TRACE_OVERLAY. A console has
 * no environment, so the trace above never turns on there and the only way to
 * ask whether the reset path did anything is to keep count and let the port
 * write it down. Nothing here changes what the port computes.
 */
static unsigned sOvReloads;   /* overlay loads that found slots */
static unsigned sOvRestores;  /* of those, the ones that restored a snapshot */
static unsigned sOvBytes;     /* bytes copied back */
static unsigned sOvDirty;     /* of those, how many had actually changed */

static int ov_trace(void)
{
    static int cached = -1;
    if (cached < 0) {
        cached = getenv("PC_TRACE_OVERLAY") != NULL;
    }
    return cached;
}

static void ov_resolve(void)
{
    int i;

    if (sOvResolved) {
        return;
    }
    sOvResolved = 1;

    if (pc_sym_count() < 0) {
#if defined(__wasm__)
        /* Nothing to wait for on wasm: the table is part of the build, so
           an unanswered one is a module whose post-link patch
           (pc/wasm/patch_ov_addrs.py) never ran, and running on would
           never reset an overlay's statics. */
        pc_wasm_fatalf("pc_ov: %s", pc_sym_error());
#endif
        /* Windows has no ELF reader yet. First load is CRT init; a later
           load will say so once rather than pretend the statics reset. */
        sOvNoSymtab = 1;
        return;
    }

    for (i = 0; i < pc_ov_static_desc_n; i++) {
        const struct pc_ov_static_desc *d = &pc_ov_static_desc[i];
        uint32_t addrs[8];
        int n;

        n = pc_sym_addresses(d->name, addrs, (int)(sizeof addrs / sizeof addrs[0]));
        /*
         * Dropped is not missing. A host whose linker discards unreferenced
         * definitions can keep a name the object files defined out of the
         * image entirely; the 3DS link does, twice, for two tentative
         * definitions nothing reads. There is no reset to do for those, and
         * treating them as a desynchronised list would refuse to boot over
         * four bytes that are not there.
         */
        if (n == PC_SYM_DROPPED) {
            if (ov_trace()) {
                fprintf(stderr, "pc_ov: skip %s (overlay %u): the link kept "
                        "no copy of it\n", d->name, d->overlay);
            }
            continue;
        }
        if (n <= 0) {
            fprintf(stderr, "pc_ov: %s (overlay %u) is in the generated "
                    "statics list but not in this binary's .symtab\n",
                    d->name, d->overlay);
            exit(2);
        }
        /*
         * gcc invents v0.2-style names for unnamed file-local objects, and
         * those collide across TUs, 8 names in the table have more than
         * one address in the binary. Snapshotting every match would reset
         * a MAIN-binary static that shares the name. A name that is unique
         * is the one we can assign; the rest stay as they are (and are
         * small compiler temporaries, not the named statics).
         */
        if (n != 1) {
            if (ov_trace()) {
                fprintf(stderr, "pc_ov: skip %s (overlay %u): %d addresses "
                        "in .symtab, cannot assign without a file\n",
                        d->name, d->overlay, n);
            }
            continue;
        }
        {
            uint32_t sz = 0;
            int ndup = 0;

            if (sOvSlotN >= PC_OV_SLOT_MAX) {
                fprintf(stderr, "pc_ov: more than %d writable overlay statics\n",
                        PC_OV_SLOT_MAX);
                exit(2);
            }
            if (pc_sym_lookup(d->name, NULL, &sz, &ndup) && ndup == 1
                    && sz != 0 && sz != d->size) {
                fprintf(stderr, "pc_ov: %s size %u in .symtab, %u in the "
                        "object nm, regenerate overlay_statics.c\n",
                        d->name, (unsigned)sz, d->size);
                exit(2);
            }
            sOvSlots[sOvSlotN].overlay = d->overlay;
            sOvSlots[sOvSlotN].addr = (void *)(unsigned long)addrs[0];
            sOvSlots[sOvSlotN].size = d->size;
            sOvSlots[sOvSlotN].snap = NULL;
            sOvSlotN++;
        }
    }
}

static void ov_reload(unsigned id)
{
    int i, n, restored;
    unsigned dirty, bytes;
    int nth;

    ov_resolve();

    if (id < (unsigned)(sizeof sOvLoads / sizeof sOvLoads[0])) {
        sOvLoads[id]++;
        nth = (int)sOvLoads[id];
    } else {
        nth = 1;
    }

    if (sOvNoSymtab) {
        if (nth > 1 && !sOvWarnedNoSym) {
            sOvWarnedNoSym = 1;
            fprintf(stderr, "pc_ov: overlay %u reloaded with no host snapshot "
                    "(%s); statics were not reset\n",
                    id, pc_sym_error());
            fflush(NULL);
        }
        return;
    }

    n = 0;
    restored = 0;
    dirty = 0;
    bytes = 0;
    for (i = 0; i < sOvSlotN; i++) {
        struct pc_ov_slot *s = &sOvSlots[i];
        unsigned k;

        if (s->overlay != id) {
            continue;
        }
        n++;
        bytes += s->size;
        if (s->snap == NULL) {
            s->snap = malloc(s->size);
            if (s->snap == NULL) {
                fprintf(stderr, "pc_ov: out of memory snapshotting overlay %u "
                        "(%u bytes)\n", id, s->size);
                exit(2);
            }
            memcpy(s->snap, s->addr, s->size);
        } else {
            for (k = 0; k < s->size; k++) {
                if (((unsigned char *)s->addr)[k]
                        != ((unsigned char *)s->snap)[k]) {
                    dirty++;
                }
            }
            memcpy(s->addr, s->snap, s->size);
            restored++;
        }
    }

    if (n > 0) {
        sOvReloads++;
        if (restored > 0) {
            sOvRestores++;
            sOvBytes += bytes;
            sOvDirty += dirty;
        }
    }

    if (ov_trace() && (n > 0 || nth > 1)) {
        fprintf(stderr, "pc_ov: start id=%u nth=%d slots=%d bytes=%u dirty=%u\n",
                id, nth, n, bytes, dirty);
        fflush(NULL);
    }
}

void pc_ov_totals(int *slots, unsigned *reloads, unsigned *restores,
                  unsigned *bytes, unsigned *dirty)
{
    if (slots != NULL) {
        *slots = sOvResolved ? sOvSlotN : -1;
    }
    if (reloads != NULL) {
        *reloads = sOvReloads;
    }
    if (restores != NULL) {
        *restores = sOvRestores;
    }
    if (bytes != NULL) {
        *bytes = sOvBytes;
    }
    if (dirty != NULL) {
        *dirty = sOvDirty;
    }
}

void FS_StartOverlay(FSOverlayInfo *p_ovi)
{
    u32 id;
    int i, n, ran;

    if (p_ovi == NULL) {
        return;
    }
    id = p_ovi->header.id;

#if defined(PC_GAME_DP)
    /* Diamond/Pearl run most of an overlay as recompiled code: it becomes
       resident (and its assembly data is written) before anything below
       can call into it. games/diamond/pc/src/pc_dp_overlay.c. */
    {
        extern void pc_dp_overlay_start(FSOverlayInfo *p_ovi);
        pc_dp_overlay_start(p_ovi);
    }
#endif

    /* Hardware copies the ROM image first. Do that for host statics
       before the sinit walk, so NitroStaticInit sees a fresh overlay. */
    ov_reload(id);

#if defined(PC_GAME_DP)
    /* D/P's static initialisers: the table is the ROM's, the needles below
       are Platinum's. */
    {
        extern void pc_dp_overlay_sinit(FSOverlayInfo *p_ovi);
        pc_dp_overlay_sinit(p_ovi);
    }
    return;
#endif

    /* Only the Poketch app overlays are wired. A new overlay whose
       NitroStaticInit starts mattering adds a needle, it does not get a
       silent empty walk. */
    n = 0;
    for (i = 0; i < (int)(sizeof sSinitNeedles / sizeof sSinitNeedles[0]); i++) {
        if (sSinitNeedles[i].overlay == id) {
            n++;
        }
    }
    if (n == 0) {
        return;
    }

    ran = 0;
    for (i = 0; i < (int)(sizeof sSinitNeedles / sizeof sSinitNeedles[0]); i++) {
        int j;

        if (sSinitNeedles[i].overlay != id) {
            continue;
        }
        for (j = 0; j < sSinitN; j++) {
            if (strstr(sSinit[j].file, sSinitNeedles[i].needle) != NULL) {
                sSinit[j].fn();
                ran++;
                break;
            }
        }
    }
    if (ran == 0) {
        fprintf(stderr, "pc_sinit: overlay %u loaded and no host "
                "NitroStaticInit matched; the app will call garbage "
                "(%d recorded)\n",
                (unsigned)id, sSinitN);
        exit(2);
    }
}
