/*
 * One station of the WM model's unit test: the real NitroSDK ARM9 WM library
 * driving pc_wm.c the way src/wireless_manager.c does (parent:
 * SetParentParameter -> StartParent -> StartMP; child: StartScan per channel
 * -> EndScan -> StartConnectEx -> StartMP; both: SetMPDataToPortEx on port
 * 14 one message at a time, paced by the send callback like CommSys). The
 * harness (run_wm_test.mjs) instantiates this module once per station,
 * carries datagrams between them through the np_host_net_* imports with
 * loss, duplication and reordering, and asserts on the exports below.
 *
 * Every message carries its sender's AID and sequence number and a pattern;
 * a receiver counts a message only if it is the next one in sequence, so a
 * passing run proves exactly-once, in-order, intact delivery both ways.
 */
#include <nitro/os.h>
#include <nitro/wm.h>
#include "pc_np_options.h"
#include <stdio.h>
#include <string.h>

#include "pc_wm.h"

#define EXPORT(name) __attribute__((export_name(#name)))

#define TEST_GGID 0x00000333u
#define TEST_TGID 0x1234
#define TEST_PORT 14
#define PARENT_SIZE 192
#define CHILD_SIZE 38
#define MAX_ENTRY 4

enum {
    PH_INIT = 0,
    PH_READY = 1,
    PH_SEARCH = 2,   /* parent: beaconing; child: scanning / joining */
    PH_LINKED = 3,   /* MP running with at least one partner */
    PH_DONE = 4,     /* child: disconnected by its own WM_Disconnect */
    PH_LOST = 5,     /* a partner disconnected (reason in station_reason) */
};

static u8 sWmBuf[WM_SYSTEM_BUF_SIZE] ATTRIBUTE_ALIGN(32);
static WMParentParam sPP ATTRIBUTE_ALIGN(32);
static u16 sUserGI[16] ATTRIBUTE_ALIGN(32);
static u8 sRecvBuf[4096] ATTRIBUTE_ALIGN(32);
static u8 sSendBuf[1024] ATTRIBUTE_ALIGN(32);
static WMBssDesc sBss ATTRIBUTE_ALIGN(32);
static WMScanParam sScan ATTRIBUTE_ALIGN(32);
static u16 sMsg[2][256] ATTRIBUTE_ALIGN(32);

static struct {
    int role; /* 0 parent, 1 child */
    int phase;
    int target;
    int errors;
    u32 frame;
    u16 aid;
    u16 children;
    int sending;
    int msg_sel;
    u32 tx;
    u32 rx_next[16];
    u32 rx;
    u32 dups_or_gaps;
    u16 reason;
    int scan_channel;
    int disconnect_sent;
} S;

static void fail(const char *what, int code)
{
    fprintf(stderr, "test_wm[%s]: %s (%d) at frame %u\n", S.role ? "child" : "parent", what, code, (unsigned)S.frame);
    S.errors++;
}

/* ---- receiving ---- */

static void port_cb(void *arg)
{
    WMPortRecvCallback *cb = arg;
    const u16 *d = cb->data;
    u32 seq;
    int i;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("port callback error", cb->errcode);
        return;
    }
    if (cb->state != WM_STATECODE_PORT_RECV) {
        return; /* PORT_INIT, CONNECTED, DISCONNECTED: generated by the ARM9 */
    }
    if (cb->length < 8 || d[0] != 0xC0DE || d[1] != cb->aid) {
        fail("bad message header", cb->length);
        return;
    }
    seq = d[2] | ((u32)d[3] << 16);
    /* A parent broadcasts one stream to every child; a child that joined
     * late picks it up at the first message it is given and from there on
     * must see every one exactly once, in order. */
    if (S.role == 1 && S.rx == 0 && S.dups_or_gaps == 0) {
        S.rx_next[cb->aid] = seq;
    }
    if (seq != S.rx_next[cb->aid]) {
        S.dups_or_gaps++;
        fail("out-of-sequence message", (int)seq - (int)S.rx_next[cb->aid]);
        return;
    }
    for (i = 4; i < cb->length / 2; i++) {
        if (d[i] != (u16)(seq * 7 + i)) {
            fail("corrupt payload", i);
            return;
        }
    }
    S.rx_next[cb->aid]++;
    S.rx++;
}

/* ---- sending ---- */

static void send_cb(void *arg)
{
    WMPortSendCallback *cb = arg;

    S.sending = 0;
    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("send callback error", cb->errcode);
    }
}

static void try_send(void)
{
    u16 *m;
    u16 size = S.role == 0 ? PARENT_SIZE : CHILD_SIZE;
    WMErrCode err;
    int i;

    if (S.sending || S.phase != PH_LINKED || (int)S.tx >= S.target) {
        return;
    }
    if (S.role == 0 && S.children == 0) {
        return;
    }
    m = sMsg[S.msg_sel];
    m[0] = 0xC0DE;
    m[1] = S.aid;
    m[2] = (u16)S.tx;
    m[3] = (u16)(S.tx >> 16);
    for (i = 4; i < size / 2; i++) {
        m[i] = (u16)(S.tx * 7 + i);
    }
    err = WM_SetMPDataToPortEx(send_cb, NULL, m, size, 0xFFFF, TEST_PORT, WM_PRIORITY_NORMAL);
    if (err != WM_ERRCODE_OPERATING) {
        fail("WM_SetMPDataToPortEx", err);
        return;
    }
    S.sending = 1;
    S.msg_sel ^= 1;
    S.tx++;
}

/* ---- parent ---- */

static void mp_cb(void *arg)
{
    WMStartMPCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("StartMP callback", cb->errcode);
        return;
    }
    if (cb->state == WM_STATECODE_MP_START && S.role == 1) {
        S.phase = PH_LINKED;
    }
}

static void parent_cb(void *arg)
{
    WMStartParentCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("StartParent callback", cb->errcode);
        return;
    }
    switch (cb->state) {
    case WM_STATECODE_PARENT_START: {
        WMErrCode err = WM_StartMP(mp_cb, (u16 *)sRecvBuf, (u16)WM_GetMPReceiveBufferSize(), (u16 *)sSendBuf,
                                   (u16)WM_GetMPSendBufferSize(), 1);
        if (err != WM_ERRCODE_OPERATING) {
            fail("WM_StartMP (parent)", err);
        }
        break;
    }
    case WM_STATECODE_CONNECTED:
        if (cb->ssid[0] != 'T' || memcmp(&cb->ssid[1], "DP", 3) != 0) {
            fail("child ssid not carried", cb->ssid[0]);
        }
        S.children |= (u16)(1u << cb->aid);
        S.rx_next[cb->aid] = 0;
        S.phase = PH_LINKED;
        break;
    case WM_STATECODE_DISCONNECTED:
        S.children &= (u16) ~(1u << cb->aid);
        S.reason = cb->reason;
        S.phase = S.children ? PH_LINKED : PH_LOST;
        break;
    default:
        break;
    }
}

static void set_pparam_cb(void *arg)
{
    WMCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("SetParentParameter callback", cb->errcode);
        return;
    }
    if (WM_StartParent(parent_cb) != WM_ERRCODE_OPERATING) {
        fail("WM_StartParent", 0);
    }
}

static void start_parent(void)
{
    memset(&sPP, 0, sizeof sPP);
    memcpy(sUserGI, "HELLO-UNION-ROOM", 16);
    sPP.userGameInfo = sUserGI;
    sPP.userGameInfoLength = 16;
    sPP.ggid = TEST_GGID;
    sPP.tgid = TEST_TGID;
    sPP.entryFlag = 1;
    sPP.maxEntry = MAX_ENTRY;
    sPP.beaconPeriod = 200;
    sPP.channel = 7;
    sPP.parentMaxSize = PARENT_SIZE;
    sPP.childMaxSize = CHILD_SIZE;
    if (WM_SetParentParameter(set_pparam_cb, &sPP) != WM_ERRCODE_OPERATING) {
        fail("WM_SetParentParameter", 0);
    }
    S.phase = PH_SEARCH;
}

/* ---- child ---- */

static void start_scan(void);

static void connect_cb(void *arg)
{
    WMStartConnectCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("StartConnect callback", cb->errcode);
        return;
    }
    switch (cb->state) {
    case WM_STATECODE_CONNECTED: {
        WMErrCode err;

        S.aid = cb->aid;
        err = WM_StartMP(mp_cb, (u16 *)sRecvBuf, (u16)WM_GetMPReceiveBufferSize(), (u16 *)sSendBuf,
                         (u16)WM_GetMPSendBufferSize(), 1);
        if (err != WM_ERRCODE_OPERATING) {
            fail("WM_StartMP (child)", err);
        }
        break;
    }
    case WM_STATECODE_DISCONNECTED:
        S.reason = cb->reason;
        S.phase = PH_LOST;
        break;
    default:
        break;
    }
}

static void end_scan_cb(void *arg)
{
    static u8 ssid[WM_SIZE_CHILD_SSID];
    WMCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("EndScan callback", cb->errcode);
        return;
    }
    ssid[0] = 'T';
    memcpy(&ssid[1], "DP", 3);
    if (WM_StartConnectEx(connect_cb, &sBss, ssid, 1, WM_AUTHMODE_OPEN_SYSTEM) != WM_ERRCODE_OPERATING) {
        fail("WM_StartConnectEx", 0);
    }
}

static void scan_cb(void *arg)
{
    WMStartScanCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("StartScan callback", cb->errcode);
        return;
    }
    if (cb->state == WM_STATECODE_PARENT_FOUND && cb->gameInfoLength >= 16 && cb->gameInfo.ggid == TEST_GGID
        && (cb->gameInfo.attribute & WM_ATTR_FLAG_ENTRY)) {
        if (memcmp(cb->gameInfo.userGameInfo, "HELLO-UNION-ROOM", 16) != 0 || sBss.gameInfo.ggid != TEST_GGID) {
            fail("game info not carried", 0);
        }
        if (WM_EndScan(end_scan_cb) != WM_ERRCODE_OPERATING) {
            fail("WM_EndScan", 0);
        }
        return;
    }
    start_scan();
}

static void start_scan(void)
{
    u16 allowed = WM_GetAllowedChannel();

    if (allowed == 0 || allowed == 0x8000) {
        fail("no allowed channel", allowed);
        return;
    }
    do {
        S.scan_channel = S.scan_channel % 16 + 1;
    } while (!(allowed & (1u << (S.scan_channel - 1))));
    memset(&sScan, 0, sizeof sScan);
    sScan.scanBuf = &sBss;
    sScan.channel = (u16)S.scan_channel;
    sScan.maxChannelTime = WM_GetDispersionScanPeriod() / 3;
    memset(sScan.bssid, 0xff, sizeof sScan.bssid);
    if (WM_StartScan(scan_cb, &sScan) != WM_ERRCODE_OPERATING) {
        fail("WM_StartScan", 0);
    }
    S.phase = PH_SEARCH;
}

static void disconnect_cb(void *arg)
{
    WMCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("Disconnect callback", cb->errcode);
        return;
    }
    S.phase = PH_DONE;
}

/* ---- both ---- */

static void ind_cb(void *arg)
{
    WMIndCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("indication error", cb->errcode);
    }
}

static void init_cb(void *arg)
{
    WMCallback *cb = arg;

    if (cb->errcode != WM_ERRCODE_SUCCESS) {
        fail("Initialize callback", cb->errcode);
        return;
    }
    if (WM_SetIndCallback(ind_cb) != WM_ERRCODE_SUCCESS || WM_SetPortCallback(TEST_PORT, port_cb, NULL) != WM_ERRCODE_SUCCESS) {
        fail("callback registration", 0);
        return;
    }
    S.phase = PH_READY;
}

EXPORT(station_init) int station_init(int role, int target)
{
    memset(&S, 0, sizeof S);
    S.role = role;
    S.target = target;
    pc_wm_init();
    if (WM_Initialize(sWmBuf, init_cb, 2) != WM_ERRCODE_OPERATING) {
        fail("WM_Initialize", 0);
        return -1;
    }
    return 0;
}

EXPORT(station_frame) void station_frame(void)
{
    S.frame++;
    if (S.phase == PH_READY) {
        if (S.role == 0) {
            start_parent();
        } else {
            start_scan();
        }
    }
    if (S.role == 1 && S.phase == PH_LINKED && (int)S.tx >= S.target && (int)S.rx >= S.target && !S.sending
        && !S.disconnect_sent) {
        S.disconnect_sent = 1;
        if (WM_Disconnect(disconnect_cb, 0) != WM_ERRCODE_OPERATING) {
            fail("WM_Disconnect", 0);
        }
    }
    try_send();
    pc_wm_step(); /* the VBlank: the ARM7 answers */
}

EXPORT(station_phase) int station_phase(void) { return S.phase; }
EXPORT(station_errors) int station_errors(void) { return S.errors; }
EXPORT(station_tx) u32 station_tx(void) { return S.tx; }
EXPORT(station_rx) u32 station_rx(void) { return S.rx; }
EXPORT(station_aid) int station_aid(void) { return S.aid; }
EXPORT(station_reason) int station_reason(void) { return S.reason; }
EXPORT(station_wm_state) int station_wm_state(void)
{
    const WMStatus *st = WMi_GetStatusAddress();
    return st ? st->state : -1;
}
EXPORT(station_link_active) int station_link_active(void)
{
    return (int)pc_np_stat.link_active;
}
