#!/usr/bin/env python3
"""
gen_dispatch: the GBA code-address table behind gba_dispatch().

    gen_dispatch.py OUT.c REPORT.txt TU.sigs...

Every `F <addr> <name>` record (gbabridge.py) names the word wrapper
gw$<addr> of one compiled function. OUT.c holds them sorted by address
(Thumb bit cleared) and gba_dispatch(addr, w0..w7), a binary search that
calls the wrapper or reports the address through gba_bad_call(). An address
two TUs define (a function the ELF lists under two names, a header's static
inline compiled twice) keeps its first definition.

REPORT.txt collects the bridge's other records: `U name` (a global the ELF
does not place: the port's own, or a decomp global agbcc dropped), `M name
irsize elfsize` (a layout disagreement between clang and agbcc) and `A name
n` (a function-scope static with n candidates in its object).
"""
import os
import sys


def main():
    out, report, sigs = sys.argv[1], sys.argv[2], sys.argv[3:]
    table, other = {}, []
    for path in sigs:
        tu = os.path.basename(path)[:-5]
        for ln in open(path):
            f = ln.split()
            if not f:
                continue
            if f[0] == "F":
                addr = int(f[1], 16)
                table.setdefault(addr & ~1, (addr, f[2], tu))
            else:
                other.append(f"{tu}: {' '.join(f)}")
    rows = sorted(table.items())
    with open(out, "w") as o:
        o.write("/* generated by games/gba-common/tools/gen_dispatch.py; do not edit */\n")
        o.write("#include <stdint.h>\n\n")
        o.write("typedef uint32_t W;\ntypedef W (*gw_fn)(W, W, W, W, W, W, W, W);\n")
        for key, (addr, name, tu) in rows:
            o.write(f"W gw${addr:08x}(W, W, W, W, W, W, W, W); /* {tu}: {name} */\n")
        o.write(f"\n#define GW_COUNT {len(rows)}\n")
        o.write("static const uint32_t k_addr[GW_COUNT] = {\n")
        for key, _ in rows:
            o.write(f"    0x{key:08x},\n")
        o.write("};\nstatic const gw_fn k_fn[GW_COUNT] = {\n")
        for _key, (addr, _n, _t) in rows:
            o.write(f"    gw${addr:08x},\n")
        o.write("};\n\n")
        o.write("""__attribute__((noreturn)) void gba_bad_call(uint32_t addr);

/* Calls the compiled function at GBA code address `addr` (either Thumb bit)
 * with up to eight argument words; returns its result word. */
uint32_t gba_dispatch(uint32_t addr, W a0, W a1, W a2, W a3, W a4, W a5, W a6, W a7) {
    uint32_t key = addr & ~1u;
    uint32_t lo = 0, hi = GW_COUNT;
    while (lo < hi) {
        uint32_t mid = (lo + hi) >> 1;
        if (k_addr[mid] < key)
            lo = mid + 1;
        else
            hi = mid;
    }
    if (lo < GW_COUNT && k_addr[lo] == key)
        return k_fn[lo](a0, a1, a2, a3, a4, a5, a6, a7);
    gba_bad_call(addr);
}

/* Whether `addr` is the entry of a compiled function. */
int gba_is_code(uint32_t addr) {
    uint32_t key = addr & ~1u, lo = 0, hi = GW_COUNT;
    while (lo < hi) {
        uint32_t mid = (lo + hi) >> 1;
        if (k_addr[mid] < key)
            lo = mid + 1;
        else
            hi = mid;
    }
    return lo < GW_COUNT && k_addr[lo] == key;
}
""")
    with open(report, "w") as r:
        r.write(f"{len(rows)} dispatchable functions\n")
        r.write("\n".join(sorted(other)) + "\n")


if __name__ == "__main__":
    main()
