#include <stdlib.h>
/*
 * The calls the shared host layer makes into Platinum-only host files,
 * answered by a Diamond/Pearl build that does not compile those files.
 *
 * pc/mk/host.mk leaves out games/platinum/pc/src's game-specific half: the
 * labs (pc_lab, pc_sprite_lab, pc_text_lab, pc_audio_lab) and
 * pc_bgm_mute.c drive Platinum's own C (Bag_*, SoundSystem_*, ...);
 * pc_modfs.c serves Platinum mods by replacing FS_OpenFile/FS_ReadFile and
 * reading Platinum NARC layouts; pc_probe2d.c reads Platinum's gSystem;
 * pc_selftest.c's suites test pc_dgt.c and pc_crypto_rc4.c, which replace
 * Platinum-SDK code D runs as its own recompiled DGT; mods_manifest.c is
 * generated by Platinum's makefile. The machine model calls them
 * unconditionally (each decides from an environment variable that it has
 * nothing to do), so the call sites stay and these are the answers, the
 * way games/platinum/3ds/src/3ds_hooks.c answers the same calls on the
 * 3DS. Strong, not weak: bringing one of the files back to D is a
 * multiple-definition error and therefore a decision.
 *
 * The signatures are the call sites' (pc_video.c, pc_os_lite.c, pc_main.c,
 * pc_dma.c, pc_mi.c), which declare them locally.
 */
#include <stdint.h>
#include <stdio.h>

/* pc_video.c's per-frame lab hooks. */
/* pc_lab_frame is also D's per-frame diagnostic point: PC_DP_HEAPCHECK=1
 * validates the game's heaps every frame, =2 on every Heap_Alloc/Heap_Free
 * as well (pc/patches/arm9/src/heap.c.patch). */
extern void pc_dp_heap_check(const char *where);
extern int pc_dp_heapcheck_level;
extern unsigned long long pc_dp_heapcheck_frame;
void pc_lab_frame(unsigned long long frame)
{
    static int init;
    if (!init) {
        const char *e = getenv("PC_DP_HEAPCHECK");
        pc_dp_heapcheck_level = e ? atoi(e) : 0;
        init = 1;
    }
    pc_dp_heapcheck_frame = frame;
    if (pc_dp_heapcheck_level >= 1) pc_dp_heap_check("frame");
}
void pc_lab_battle_frame(unsigned long long frame) { (void)frame; }
void pc_lab_save_frame(unsigned long long frame) { (void)frame; }
void pc_lab_grow_frame(unsigned long long frame) { (void)frame; }
void pc_lab_contest_frame(unsigned long long frame) { (void)frame; }
void pc_lab_underground_frame(unsigned long long frame) { (void)frame; }
void pc_lab_sprite_frame(unsigned long long frame) { (void)frame; }
void pc_lab_text_frame(unsigned long long frame) { (void)frame; }
void pc_lab_audio_frame(unsigned long long frame) { (void)frame; }

/* pc_video.c: PC_PROBE_2D, a sprite-state probe over Platinum's gSystem. */
void pc_probe2d(uint64_t frame) { (void)frame; }

/* pc_dma.c / pc_mi.c: PC_TRACE_LCDC lives in pc_probe2d.c beside the probe. */
void pc_trace_lcdc(const char *who, const void *src, uint32_t dst, uint32_t size)
{
    (void)who; (void)src; (void)dst; (void)size;
}

/* pc_os_lite.c's OS_Halt: PC_MUTE_BGM pauses Platinum's BGM players. */
void pc_bgm_mute_apply(void) {}

/* pc_main.c: mods are a Platinum feature (pc/mods, pc_modfs.c). */
const char pc_mods_manifest[] = "";
void pc_modfs_boot(void) {}

/* pc_main.c: PC_SELFTEST. The suites are Platinum's host replacements;
 * say so rather than report a pass nothing ran. */
int pc_selftest_run(FILE *out)
{
    if (out == NULL) {
        out = stderr;
    }
    fprintf(out, "pc-selftest: the self-test suites test Platinum's host "
                 "replacements and are not built for Diamond/Pearl\n");
    return 0;
}

/* pc_view.c: the frame-boundary options hook (pc/include/pc_np_options.h,
 * declared weak). Platinum's lives in pc_np_field.c and drives its
 * FieldSystem; D has no equivalent yet. Defined rather than left weak-
 * undefined because the bridge takes its address for the table
 * (bridge_adapters.c), which needs a definition. */
void pc_np_frame(void) {}
