#!/usr/bin/env python3
"""
Generate the stack-argument trampolines for decompiled C -> recompiled calls.

What this is for. ARM passes arguments five and up on the
stack; a recompiled body reads them off the *emulated* stack and a decompiled C
caller pushed them on the host one, so they arrived as whatever the host stack
held. 2.5 fixed the forward direction and measured this one as a ceiling. The
live defect it hid: arm7/lib/src/SND_main.c calls the ARM7's own

    OS_SetPeriodicAlarm(&sAlarm, tick + 0x10000, 2728, sub_037fc330, NULL)

-- seven words, because OSTick is 64 bits, so the handler and its argument
were zeros, the 192 Hz alarm that wakes SndThread was armed with a NULL
callback, and the sound thread never took a tick.

What is generated, and it is deliberately one line each: every trampoline is a
call to armrec_stkargs_call() in armrec_rt.c, which is where the model lives and
the only place it can be got wrong. The generated file has no arithmetic in it.

Where the names come from. icall_thunk.py writes one sidecar per object naming
exactly the functions whose direct calls it rewrote in that object, so this
generates a trampoline for each name that has a call site and for no others.
Two lists that could disagree would be the 1.8 defect again; there is one list
and the rewriter owns it.

The declaration is armrec's four-word one and that is not a claim about arity.
The trampoline immediately casts to armrec_extfn to make the call, so the
declaration exists only to name the symbol; the twenty words it then passes are
what the callee's own prototype reads from. See armrec_rt.h.
"""

import argparse
import os
import sys

PREFIX = "armrec_stk_"

HEADER = '''/*
 * GENERATED by tools/armrec/gen_stkargs.py, do not edit.
 *
 * One stack-argument trampoline per recompiled function that decompiled C
 * calls directly. The model is in tools/armrec/armrec_rt.h above
 * armrec_stkargs_call(); this file deliberately holds no logic.
 */
#include "armrec_rt.h"

#define ARMREC_STK(name)                                                      \\
    extern uint64_t name(uint32_t, uint32_t, uint32_t, uint32_t);             \\
    uint64_t %(prefix)s##name(uint32_t, uint32_t, uint32_t, uint32_t,         \\
                              ARMREC_STK_PARAMS);                             \\
    uint64_t %(prefix)s##name(uint32_t a0, uint32_t a1, uint32_t a2,          \\
                              uint32_t a3, ARMREC_STK_PARAMS) {               \\
        return armrec_stkargs_call((armrec_extfn)name, a0, a1, a2, a3,        \\
                                   ARMREC_STK_FORWARD);                       \\
    }

''' % {"prefix": PREFIX}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("sidecar", nargs="*",
                    help=".stk files written by icall_thunk.py")
    ns = ap.parse_args()

    names = set()
    for path in ns.sidecar:
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            for line in fh:
                name = line.strip()
                if name:
                    names.add(name)

    body = HEADER + "".join("ARMREC_STK(%s)\n" % n for n in sorted(names))

    # Compare and swap: this target is rebuilt every time because one of its
    # inputs can never be up to date (pc/Makefile says why for the sibling
    # generator), and rewriting an identical file would recompile it and relink
    # for nothing.
    try:
        with open(ns.out) as fh:
            if fh.read() == body:
                print(len(names))
                return 0
    except OSError:
        pass
    with open(ns.out, "w") as fh:
        fh.write(body)
    print(len(names))
    return 0


if __name__ == "__main__":
    sys.exit(main())
