#!/usr/bin/env python3
"""
gen_bridge: the C half of the typed C <-> recompiled bridge (wasm32 only).

Usage:
    gen_bridge.py --classes classes.txt --out DIR [--root DIR] SIGS...
    gen_bridge.py --classes classes.txt --out DIR --sigs-list FILE

Reads the per-TU records irbridge.py writes (see its docstring for the
format) and generates, in DIR:

  bridge_calls.c     aw$<sig>$F: decompiled C -> recompiled F, marshalling
                     the call site's arguments into r0..r3 + emulated-stack
                     words (rewrite 1); ai$<sig>: an indirect call from C,
                     native when the pointer is a table index, armrec_dispatch
                     otherwise (rewrite 4)
  bridge_adapters.c  c2u$F: recompiled code -> C function F with its real
                     prototype (rewrite 6), one for every `B` name in
                     classes.txt, every `X` name that is a C function, and
                     every C function whose address C takes; plus
                     armrec_bridge_table, the table index -> adapter map
                     armrec_dispatch() uses for values < 0x00100000 (rewrite 7)
  bridge_externs.c   armrec_ext_<name> for every B/X name and
                     armrec_bind_externs(): table index for a function,
                     address for data (rewrite 7; armrec --wasm leaves this to
                     the bridge because only the C side knows the kind)
  bridge_report.txt  unresolved names (a B name no C defines gets a trap
                     adapter that names it; an X name of unknown kind binds to
                     0), signature conflicts, and signature statistics

Each output is rewritten only when its content changes, so an incremental
build recompiles a generated file only when the bridge really changed.

The marshalling is described in armrec_bridge.h. Every C callee is declared
under an asm label (`extern T bf_N(...) __asm__("F")`) with a prototype
derived from the defining TU's IR signature, so the wasm signature matches
the definition exactly and no header's prototype of the same symbol can
collide.
"""

import argparse
import os
import re
import sys
from collections import Counter, defaultdict

STACK_WORDS = 16      # ARMREC_EXT_STACK_WORDS / ARMREC_BRIDGE_VA_STACK_WORDS

TOKEN_RE = re.compile(r"[vbhactswilpfd]|[yr]\d+")


class Sig(object):
    def __init__(self, text):
        self.text = text
        parts = text.split("_")
        if len(parts) not in (2, 3):
            raise ValueError("bad signature %r" % text)
        self.ret = parts[0]
        self.params = TOKEN_RE.findall(parts[1])
        if "".join(self.params) != parts[1] or not TOKEN_RE.fullmatch(self.ret):
            raise ValueError("bad signature %r" % text)
        self.nfixed = None
        if len(parts) == 3:
            if not parts[2].startswith("v"):
                raise ValueError("bad signature %r" % text)
            self.nfixed = int(parts[2][1:])

    @property
    def variadic(self):
        return self.nfixed is not None

    def sret(self):
        return self.params[0] if self.params and self.params[0][0] == "r" else None


def nwords(tok):
    if tok in ("l", "d"):
        return 2
    if tok[0] == "y":
        return (int(tok[1:]) + 3) // 4
    if tok[0] == "r":
        return 1 if int(tok[1:]) > 4 else 0
    return 1


# C types at the wasm boundary. Every integer of 32 bits or fewer and every
# pointer is uint32_t (all are wasm i32; the value conversion is explicit).
def c_type(tok):
    if tok == "v":
        return "void"
    if tok == "l":
        return "uint64_t"
    if tok == "f":
        return "float"
    if tok == "d":
        return "double"
    if tok[0] in "yr":
        return "void *"
    return "uint32_t"


def narrow(tok, expr):
    """A 32-bit word -> the value of an i1/i8/i16 token, as uint32_t."""
    return {
        "b": "(uint32_t)((uint8_t)(%s) != 0)",
        "h": "(uint32_t)(uint8_t)(%s)",
        "a": "(uint32_t)(int32_t)(int8_t)(%s)",
        "c": "(uint32_t)(uint8_t)(%s)",
        "t": "(uint32_t)(uint16_t)(%s)",
        "s": "(uint32_t)(int32_t)(int16_t)(%s)",
        "w": "(uint32_t)(uint16_t)(%s)",
        "i": "(uint32_t)(%s)",
        "p": "(uint32_t)(%s)",
    }[tok] % expr


def ret_c_type(sig):
    return "void" if sig.sret() else c_type(sig.ret)


PRELUDE = """\
/* Generated by games/platinum/tools/armrec/gen_bridge.py. Do not edit. */
#include <stdint.h>
#include "armrec_bridge.h"

extern uint32_t armrec_sp;
uint64_t armrec_dispatch(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
uint32_t armrec_extern_addr(const char *, void *);

static inline uint32_t bw_f2w(float f) { uint32_t w; __builtin_memcpy(&w, &f, 4); return w; }
static inline uint64_t bw_d2l(double d) { uint64_t w; __builtin_memcpy(&w, &d, 8); return w; }
static inline float bw_w2f(uint32_t w) { float f; __builtin_memcpy(&f, &w, 4); return f; }
static inline double bw_l2d(uint64_t w) { double d; __builtin_memcpy(&d, &w, 8); return d; }
static inline uint32_t bw_stk(uint32_t k) {
    uint32_t v;
    __builtin_memcpy(&v, (const void *)(uintptr_t)(armrec_sp + 4u * k), 4);
    return v;
}
static inline void bw_put(uint32_t sp, uint32_t k, uint32_t v) {
    __builtin_memcpy((void *)(uintptr_t)(sp + 4u * k), &v, 4);
}
"""


def write_if_changed(path, text):
    try:
        with open(path) as f:
            if f.read() == text:
                return False
    except IOError:
        pass
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)
    return True


def sanitize(name):
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


# ---------------------------------------------------------------------------
# C -> recompiled: marshal a parameter list into words
# ---------------------------------------------------------------------------

def marshal(sig, out, ind="    "):
    """Emit code filling `w[]` from parameters a0..; returns (word count,
    sret pointer expr or None, sret size)."""
    n = sum(nwords(t) for t in sig.params)
    has_agg = any(t[0] == "y" for t in sig.params)
    if n:
        out.append("%suint32_t w[%d]%s;" % (ind, n, " = {0}" if has_agg else ""))
    k = 0
    sret = None
    sret_size = 0
    for i, t in enumerate(sig.params):
        a = "a%d" % i
        if t[0] == "r":
            sret = a
            sret_size = int(t[1:])
            if sret_size > 4:
                out.append("%sw[%d] = (uint32_t)(uintptr_t)%s;" % (ind, k, a))
        elif t[0] == "y":
            out.append("%s__builtin_memcpy(&w[%d], %s, %d);" % (ind, k, a, int(t[1:])))
        elif t == "l":
            out.append("%sw[%d] = (uint32_t)%s; w[%d] = (uint32_t)(%s >> 32);"
                       % (ind, k, a, k + 1, a))
        elif t == "d":
            out.append("%s{ uint64_t q = bw_d2l(%s); w[%d] = (uint32_t)q; "
                       "w[%d] = (uint32_t)(q >> 32); }" % (ind, a, k, k + 1))
        elif t == "f":
            out.append("%sw[%d] = bw_f2w(%s);" % (ind, k, a))
        else:
            out.append("%sw[%d] = %s;" % (ind, k, narrow(t, a)))
        k += nwords(t)
    return n, sret, sret_size


def emit_ucall(sig, call_fmt, out, ind="    "):
    """Marshal, call (call_fmt % 'r0, r1, r2, r3' words), convert the packed
    return. call_fmt receives the four register expressions."""
    n, sret, sret_size = marshal(sig, out, ind)
    regs = ", ".join(("w[%d]" % i) if i < n else "0" for i in range(4))
    ns = max(0, n - 4)
    if ns:
        out.append("%suint32_t sv = armrec_sp;" % ind)
        out.append("%suint32_t sp = (sv - %du) & ~7u;" % (ind, 4 * ns))
        for j in range(ns):
            out.append("%sbw_put(sp, %d, w[%d]);" % (ind, j, 4 + j))
        out.append("%sarmrec_sp = sp;" % ind)
    out.append("%suint64_t r = %s;" % (ind, call_fmt % regs))
    if ns:
        out.append("%sarmrec_sp = sv;" % ind)
    out.append("%s(void)r;" % ind)
    if sret is not None:
        if sret_size <= 4:
            out.append("%s{ uint32_t r0 = (uint32_t)r; __builtin_memcpy(%s, &r0, %d); }"
                       % (ind, sret, sret_size))
        return
    t = sig.ret
    if t == "v":
        return
    if t == "l":
        out.append("%sreturn r;" % ind)
    elif t == "f":
        out.append("%sreturn bw_w2f((uint32_t)r);" % ind)
    elif t == "d":
        out.append("%sreturn bw_l2d(r);" % ind)
    else:
        out.append("%sreturn %s;" % (ind, narrow(t, "(uint32_t)r")))


def param_list(sig, first=None):
    ps = [] if first is None else [first]
    ps += ["%s a%d" % (c_type(t), i) for i, t in enumerate(sig.params)]
    return ", ".join(ps) if ps else "void"


def gen_wrapper(sig, name, label, out):
    out.append("%s aw$%s$%s(%s) {" % (ret_c_type(sig), sig.text, name, param_list(sig)))
    emit_ucall(sig, label + "(%s)", out)
    out.append("}")


def gen_indirect(sig, out, bb_sizes):
    rt = ret_c_type(sig)
    out.append("%s ai$%s(%s) {" % (rt, sig.text, param_list(sig, "uint32_t fp")))
    out.append("    if (fp < ARMREC_WASM_FNPTR_END) {")
    nfix = sig.nfixed if sig.variadic else len(sig.params)
    ptypes = [c_type(t) for t in sig.params[:nfix]]
    if sig.variadic:
        ptypes.append("...")
    args = []
    for i, t in enumerate(sig.params):
        if i >= nfix and t[0] == "y":
            sz = int(t[1:])
            bb_sizes.add(sz)
            args.append("*(const struct bw_bb%d *)a%d" % (sz, i))
        else:
            args.append("a%d" % i)
    call = "((%s (*)(%s))(uintptr_t)fp)(%s)" % (
        rt, ", ".join(ptypes) if ptypes else "void", ", ".join(args))
    out.append("        %s%s;" % ("" if rt == "void" else "return ", call))
    if rt == "void":
        out.append("        return;")
    out.append("    }")
    emit_ucall(sig, "armrec_dispatch(fp, %s)", out)
    out.append("}")


# ---------------------------------------------------------------------------
# recompiled -> C: read words, call with the real prototype
# ---------------------------------------------------------------------------

def word(k):
    return "r%d" % k if k < 4 else "bw_stk(%d)" % (k - 4)


def gen_adapter(sym, sig, label, out):
    out.append("uint64_t c2u$%s(uint32_t r0, uint32_t r1, uint32_t r2, uint32_t r3) {" % sym)
    body = []
    args = []
    k = 0
    sret_tmp = None
    nfix = sig.nfixed if sig.variadic else len(sig.params)
    for i, t in enumerate(sig.params[:nfix]):
        if t[0] == "r":
            size = int(t[1:])
            if size > 4:
                args.append("(void *)(uintptr_t)%s" % word(k))
                sret_tmp = ("ptr", word(k))
            else:
                body.append("    uint64_t rb[1] = {0};")
                args.append("(void *)rb")
                sret_tmp = ("buf", None)
        elif t[0] == "y":
            nw = (int(t[1:]) + 3) // 4
            body.append("    uint64_t yb%d[%d];" % (i, (nw + 1) // 2))
            for j in range(nw):
                body.append("    { uint32_t v = %s; __builtin_memcpy((char *)yb%d + %d, &v, 4); }"
                            % (word(k + j), i, 4 * j))
            args.append("(void *)yb%d" % i)
        elif t == "l":
            args.append("((uint64_t)%s | (uint64_t)%s << 32)" % (word(k), word(k + 1)))
        elif t == "d":
            args.append("bw_l2d((uint64_t)%s | (uint64_t)%s << 32)" % (word(k), word(k + 1)))
        elif t == "f":
            args.append("bw_w2f(%s)" % word(k))
        else:
            args.append(narrow(t, word(k)))
        k += nwords(t)
    if sig.variadic:
        # The callee's own format decides how many it reads; hand it every
        # register left and the stack ceiling, as words.
        for j in range(k, 4 + STACK_WORDS):
            args.append(word(j))
    out.extend(body)
    call = "%s(%s)" % (label, ", ".join(args))
    if sret_tmp is not None:
        out.append("    %s;" % call)
        if sret_tmp[0] == "buf":
            out.append("    return (uint32_t)rb[0];")
        else:
            out.append("    return %s;" % sret_tmp[1])
    elif sig.ret == "v":
        out.append("    %s;" % call)
        out.append("    return 0;")
    elif sig.ret == "l":
        out.append("    return %s;" % call)
    elif sig.ret == "f":
        out.append("    return bw_f2w(%s);" % call)
    elif sig.ret == "d":
        out.append("    return bw_d2l(%s);" % call)
    else:
        out.append("    return %s;" % narrow(sig.ret, call))
    out.append("}")


def c_proto(sig, label, sym):
    ps = [c_type(t) for t in sig.params[:sig.nfixed if sig.variadic else None]]
    if sig.variadic:
        ps.append("...")
    return 'extern %s %s(%s) __asm__("%s");' % (
        ret_c_type(sig), label, ", ".join(ps) if ps else "void", sym)


# ---------------------------------------------------------------------------

def load_classes(path):
    F, D, B, X = {}, {}, set(), set()
    with open(path) as f:
        for ln in f:
            p = ln.split()
            if not p or p[0].startswith("#"):
                continue
            if p[0] == "F":
                F[p[1]] = int(p[2], 16)
            elif p[0] == "D":
                D[p[1]] = int(p[2], 16)
            elif p[0] == "B":
                B.add(p[1])
            elif p[0] == "X":
                X.add(p[1])
    return F, D, B, X


def main():
    ap = argparse.ArgumentParser(description="generate the bridge's C side")
    ap.add_argument("--classes", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--root", default="", help="directory SIGS are relative to")
    ap.add_argument("--sigs-list", help="file naming one .sigs per line")
    ap.add_argument("sigs", nargs="*")
    args = ap.parse_args()

    paths = list(args.sigs)
    if args.sigs_list:
        with open(args.sigs_list) as f:
            paths += [ln.strip() for ln in f if ln.strip()]
    paths = [os.path.join(args.root, p) for p in paths]

    F, Dd, B, X = load_classes(args.classes)

    defs = {}                 # name -> (sig, strength, tu)
    conflicts = []
    data = set()
    taken = {}                # sym -> (sig, name)
    wrappers = set()          # (sig, name)
    indirects = set()
    declared = defaultdict(set)
    missing = []
    for p in paths:
        try:
            f = open(p)
        except IOError:
            missing.append(p)
            continue
        with f:
            for ln in f:
                r = ln.split()
                if not r:
                    continue
                k = r[0]
                if k == "D":
                    name, sig, strength = r[1], r[2], r[3]
                    old = defs.get(name)
                    if old is None or (old[1] == "weak" and strength == "strong"):
                        if old is not None and old[0] != sig:
                            conflicts.append("%s: %s (%s) vs %s (%s)" % (
                                name, old[0], old[2], sig, p))
                        defs[name] = (sig, strength, p)
                    elif old[0] != sig:
                        conflicts.append("%s: %s (%s) vs %s (%s)" % (
                            name, old[0], old[2], sig, p))
                elif k == "G":
                    data.add(r[1])
                elif k == "T":
                    taken.setdefault(r[1], (r[2], r[3]))
                elif k == "W":
                    wrappers.add((r[1], r[2]))
                elif k == "I":
                    indirects.add(r[1])
                elif k == "E":
                    declared[r[1]].add(r[2])
    if missing:
        sys.stderr.write("gen_bridge: %d .sigs files are missing (objects built "
                         "without BRIDGE_COMPILE? delete them and rebuild), "
                         "first: %s\n" % (len(missing), missing[0]))
        return 1

    labels = {}

    def label(sym):
        if sym not in labels:
            labels[sym] = "bf_%d" % len(labels)
        return labels[sym]

    # ---- bridge_calls.c --------------------------------------------------
    out = [PRELUDE]
    asm_callees = sorted(set(n for _s, n in wrappers))
    for n in asm_callees:
        if n not in F:
            sys.stderr.write("gen_bridge: wrapper target %s is not an F name in "
                             "%s (classes changed under a stale object?)\n"
                             % (n, args.classes))
            return 1
        out.append('extern uint64_t %s(uint32_t, uint32_t, uint32_t, uint32_t) '
                   '__asm__("%s");' % (label(n), n))
    out.append("")
    bb_sizes = set()
    body = []
    for s, n in sorted(wrappers):
        gen_wrapper(Sig(s), n, label(n), body)
        body.append("")
    for s in sorted(indirects):
        gen_indirect(Sig(s), body, bb_sizes)
        body.append("")
    for sz in sorted(bb_sizes):
        out.append("struct bw_bb%d { uint8_t b[%d]; };" % (sz, sz))
    out.append("")
    out.extend(body)
    calls_c = "\n".join(out) + "\n"

    # ---- bridge_adapters.c -----------------------------------------------
    # sym -> (sig, display name, resolved?)
    adapters = {}
    unresolved_b = []
    for n in sorted(B):
        if n in defs:
            adapters[n] = (defs[n][0], n)
        else:
            unresolved_b.append(n)
    x_kind = {}
    for n in sorted(X):
        if n in defs:
            x_kind[n] = "func"
            adapters.setdefault(n, (defs[n][0], n))
        elif n in data:
            x_kind[n] = "data"
        elif n in taken:
            x_kind[n] = "func"
            adapters.setdefault(n, taken[n])
        else:
            x_kind[n] = None
    for sym, (s, n) in sorted(taken.items()):
        if sym in F or n in F:
            continue
        # A definition's signature beats the taker's declaration.
        if sym == n and n in defs:
            s = defs[n][0]
        adapters.setdefault(sym, (s, n))

    out = [PRELUDE]
    for sym in sorted(adapters):
        out.append(c_proto(Sig(adapters[sym][0]), label(sym), sym))
    out.append("")
    for sym in sorted(adapters):
        gen_adapter(sym, Sig(adapters[sym][0]), label(sym), out)
        out.append("")
    for n in unresolved_b:
        out.append("uint64_t c2u$%s(uint32_t r0, uint32_t r1, uint32_t r2, uint32_t r3) {" % n)
        out.append("    (void)r0; (void)r1; (void)r2; (void)r3;")
        out.append('    armrec_bridge_unresolved("%s");' % n)
        out.append("}")
        out.append("")
    out.append("const struct armrec_bridge_ent armrec_bridge_table[] = {")
    for sym in sorted(adapters):
        out.append('    { (void *)%s, c2u$%s, "%s" },' % (label(sym), sym, adapters[sym][1]))
    if not adapters:
        out.append("    { 0, 0, 0 },")
    out.append("};")
    out.append("const uint32_t armrec_bridge_table_count = %d;" % len(adapters))
    adapters_c = "\n".join(out) + "\n"

    # ---- bridge_externs.c ------------------------------------------------
    out = [PRELUDE]
    ext_names = sorted(B | X)
    decls = []
    binds = []
    unresolved_x = []
    for n in ext_names:
        out.append("uint32_t armrec_ext_%s;" % sanitize(n))
        if n in adapters:
            kind = "func"
        elif n in B:
            kind = None          # unresolved B: its adapter traps
        else:
            kind = x_kind.get(n)
        if kind == "func":
            decls.append(c_proto(Sig(adapters[n][0]), label(n), n))
            binds.append('    armrec_ext_%s = armrec_extern_addr("%s", (void *)%s);'
                         % (sanitize(n), n, label(n)))
        elif kind == "data":
            decls.append('extern char %s __asm__("%s");' % (label(n), n))
            binds.append('    armrec_ext_%s = armrec_extern_addr("%s", (void *)&%s);'
                         % (sanitize(n), n, label(n)))
        elif n in X:
            unresolved_x.append(n)
    out.append("")
    out.extend(decls)
    out.append("")
    out.append("void armrec_bind_externs(void) {")
    out.extend(binds)
    out.append("}")
    externs_c = "\n".join(out) + "\n"

    # ---- report ------------------------------------------------------------
    rep = []
    rep.append("# gen_bridge report: %d TUs, %d defined functions, %d data, "
               "%d address-taken" % (len(paths), len(defs), len(data), len(taken)))
    rep.append("# %d aw$ wrappers (%d signatures, %d asm callees), %d ai$ "
               "adapters, %d c2u$ adapters, %d extern names"
               % (len(wrappers), len(set(s for s, _ in wrappers)),
                  len(asm_callees), len(indirects), len(adapters), len(ext_names)))
    rep.append("")
    rep.append("# unresolved B: recompiled code calls these, no C TU defines "
               "them; their c2u$ adapter traps by name (%d)" % len(unresolved_b))
    for n in unresolved_b:
        hint = declared.get(n)
        rep.append("B %s%s" % (n, ("   declared as " + ",".join(sorted(hint)))
                               if hint else ""))
    rep.append("")
    rep.append("# unresolved X: recompiled code takes the address, no C TU "
               "defines it; armrec_ext_ stays 0 (%d)" % len(unresolved_x))
    for n in unresolved_x:
        rep.append("X %s" % n)
    rep.append("")
    rep.append("# signature conflicts between definitions (%d)" % len(conflicts))
    rep.extend("! " + c for c in conflicts)
    rep.append("")
    rep.append("# signatures: wrapper (C -> recompiled) call sites by signature")
    for s, c in Counter(s for s, _ in wrappers).most_common():
        rep.append("W %6d %s" % (c, s))
    rep.append("# indirect call signatures")
    for s in sorted(indirects):
        rep.append("I %s" % s)
    rep.append("# adapter (recompiled -> C) signatures")
    for s, c in Counter(v[0] for v in adapters.values()).most_common():
        rep.append("A %6d %s" % (c, s))
    report = "\n".join(rep) + "\n"

    os.makedirs(args.out, exist_ok=True)
    for fname, text in (("bridge_calls.c", calls_c),
                        ("bridge_adapters.c", adapters_c),
                        ("bridge_externs.c", externs_c),
                        ("bridge_report.txt", report)):
        write_if_changed(os.path.join(args.out, fname), text)
    if unresolved_b or unresolved_x:
        sys.stderr.write("gen_bridge: %d unresolved B, %d unresolved X names "
                         "(see %s)\n" % (len(unresolved_b), len(unresolved_x),
                                         os.path.join(args.out, "bridge_report.txt")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
