#!/usr/bin/env python3
"""
Definitions for the ARM7 functions strip_asm.py had to remove, as traps.

Five of the thirty files in arm7/lib/src mix ordinary C with CodeWarrior `asm`
function bodies, exactly as 28 files under arm9/ do. The ARM7 object rule in
pc/Makefile runs strip_asm.py on them for the same reason the ARM9 one does,
without it GCC loses the whole translation unit, and OS_thread.c's scheduler
goes with it; which leaves twenty-one functions declared and undefined, and
nineteen of them referenced by other ARM7 objects.

pc/src/pc_arm7_asm.c supplies them and this traps the rest.
6.1 linked the ARM7 half and gave it its memory but no execution model,
because the two processors' I/O pages are separate hardware and the port
mapped one; armrec_cpu_switch() is what changed. All twenty-one are
implemented today, so this normally emits nothing, and it still runs,
because the list is a property of the tree and a file that gains an `asm` body
must get a trap rather than a hole. That is's rule: a wrong
OS_EnableInterrupts is a bug somewhere else entirely, hours later, and a trap
is on the spot.

What is already supplied is asked of nm, not of a list. --have takes object
files and every `arm7_NAME` they define strongly is a name not to trap. Same
argument gen_decomp_syms.py makes for reading the symbol table instead of the
sources: the object file is the one place that already knows what the compiler
kept and what the preprocessor did to the name. A hand-maintained list here
would be a second thing to update, and the failure mode, a duplicate
definition, only shows up at the link.

The names are emitted unprefixed and the namespace pass renames them along with
everything else the ARM7 half defines, so what the link sees is
arm7_OS_EnableInterrupts and the ARM9's own definition is untouched.
pc/src/pc_arm7_asm.c writes the prefix out instead, because it is an ordinary
pc/src object that the namespace pass never sees; that is what lets it call the
ARM9's implementation of the sixteen bodies that are identical.

Usage:
    gen_arm7_traps.py --out FILE [--nm NM] [--have OBJ]... INPUT.c...
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def asm_functions(path):
    """The `asm` bodies strip_asm.py removes from one file, in file order."""
    out = subprocess.run([sys.executable, os.path.join(HERE, "strip_asm.py"),
                          "--list", path],
                         stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    if out.returncode != 0:
        return []
    return [n for n in out.stdout.decode().split() if n]


def supplied(objs, nm="nm"):
    """
    The unprefixed names `objs` already define as arm7_NAME.

    A missing object is not an error: pc/Makefile orders the trap file after
    the object it names, but a hand run of this script should still work and
    report what it can rather than refusing.
    """
    names = set()
    for obj in objs:
        if not os.path.exists(obj):
            continue
        out = subprocess.run([nm, "--defined-only", obj],
                             stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        if out.returncode != 0:
            continue
        for line in out.stdout.decode().splitlines():
            f = line.split()
            if len(f) >= 3 and f[1] in "TDBRG":
                name = f[2]
                if name.startswith("_arm7_"):   # i386 PE decoration
                    name = name[1:]
                if name.startswith("arm7_"):
                    names.add(name[len("arm7_"):])
    return names


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True)
    ap.add_argument("--nm", default="nm")
    ap.add_argument("--have", action="append", default=[],
                    help="an object file whose arm7_* definitions are already "
                         "supplied; repeatable")
    ap.add_argument("sources", nargs="+")
    args = ap.parse_args()

    have = supplied(args.have, args.nm)

    found = []
    for path in sorted(args.sources):
        for name in asm_functions(path):
            if name in have:
                continue
            found.append((name, os.path.basename(path)))

    with open(args.out, "w") as f:
        f.write("/* Generated by tools/armrec/gen_arm7_traps.py, do not"
                " edit.\n"
                " * The ARM7 `asm` bodies strip_asm.py removes, as traps.\n"
                " * See that script for why a trap and not an implementation.\n"
                " */\n"
                "#include <stdio.h>\n"
                "#include <stdlib.h>\n\n"
                "/* Not static: the namespace pass keys on defined globals,\n"
                " * and a file-local helper would not be renamed with them. */\n"
                "void arm7_asm_trap(const char *name, const char *file);\n"
                "void arm7_asm_trap(const char *name, const char *file)\n"
                "{\n"
                "    fprintf(stderr,\n"
                "            \"armrec: the ARM7's %s (arm7/lib/src/%s) was \"\n"
                "            \"called, and this build has no ARM7 to run \"\n"
                "            \"it.\\n\"\n"
                "            \"  It is a CodeWarrior `asm` body, so \"\n"
                "            \"strip_asm.py removed it to let the rest of its \"\n"
                "            \"file compile, and this build links the \"\n"
                "            \"ARM7 without giving it an execution model, \"\n"
                "            \"the two processors' I/O pages are separate \"\n"
                "            \"hardware and this port maps one.\\n\", name, file);\n"
                "    abort();\n"
                "}\n\n")
        for name, src in found:
            f.write("unsigned long long %s(void);\n"
                    "unsigned long long %s(void)\n"
                    "{\n"
                    "    arm7_asm_trap(\"%s\", \"%s\");\n"
                    "    return 0;\n"
                    "}\n\n" % (name, name, name, src))
    sys.stdout.write("%d\n" % len(found))


if __name__ == "__main__":
    main()
