#!/usr/bin/env python3
"""One trainer per class, battled, so every AI script in the game gets executed.

    $ python3 pc/tests/pc_trainers.py            # every class, resumable
    $ python3 pc/tests/pc_trainers.py --report   # what the last run found
    $ python3 pc/tests/pc_trainers.py --redo trap,refused

The battle-start crash this port hit early on was an AI opcode dispatched out
of a table that had never been populated. The table is real now, 91,724 bytes
of bytecode lifted out of the ROM's assembled section by pc/gen_trainer_ai.py,
against 109 handlers, and the question this answers is whether every class's
script stays inside it.

What a row means. `clean` is the strongest verdict available cheaply: the
battle started, the enemy's AI evaluated at least one move, and the run reached
its frame limit without the dispatch check firing. The battle is NOT fought to
a conclusion, and that is deliberate; the AI runs on the enemy's first turn,
so a short run exercises the script, and fighting 102 battles to the end would
cost hours to learn nothing more about dispatch.

`trap` is the finding this exists for. `refused` means the battle never
started, which is a fact about the harness or the trainer's data rather than
about the AI, and each one gets a written reason rather than a count.

Every class is battled through the save lab: a recipe with a party strong
enough to survive a turn, and PC_LAB_BATTLE naming the trainer. Nothing is
hand-placed on a map and no story flag is needed.
"""

import argparse
import collections
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BINARY = os.path.join(ROOT, "build", "pc", "pokeplatinum")
TRAINERS = os.path.join(ROOT, "res", "trainers", "data")
IDS = os.path.join(ROOT, "build", "pc", "geninclude", "generated", "trainers.h")
WORK = os.path.join(ROOT, "build", "pc", "trainers")
RESULTS = os.path.join(WORK, "results.json")
REPLAY = os.path.join(ROOT, "pc", "replays", "lab-battle.txt")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pc_lab   # noqa: E402

# Long enough for the intro, the CONTINUE option, the map, the encounter
# transition and the enemy's first evaluated turn, measured at about 3,900
# frames for the first AI dispatch, so this is that plus room.
FRAMES = 6000
BATTLE_AT = 2600

# A lead that survives one turn against anything in the game, so that a
# `refused` row is never just "the player fainted before the AI thought".
RECIPE = """# Generated by pc/tests/pc_trainers.py, one trainer per class.
name AICHECK
gender GENDER_MALE
trainer-id 40001
money 60000
badge BADGE_ID_COAL
badge BADGE_ID_FOREST
badge BADGE_ID_COBBLE
badge BADGE_ID_FEN
badge BADGE_ID_RELIC
badge BADGE_ID_MINE
badge BADGE_ID_ICICLE
badge BADGE_ID_BEACON
party SPECIES_GARCHOMP 100 ITEM_NONE
party SPECIES_MILOTIC 100 ITEM_NONE
party-move 0 0 MOVE_EARTHQUAKE
party-move 1 0 MOVE_SURF
map MAP_HEADER_JUBILIFE_CITY 0xB4 0x309 FACE_DOWN
"""


def trainer_ids():
    out = {}
    with open(IDS) as f:
        for line in f:
            m = re.match(r"\s*(TRAINER_[A-Z0-9_]+)\s*=\s*(\d+)", line)
            if m:
                out[m.group(1)] = int(m.group(2))
    if not out:
        sys.exit("pc_trainers: %s carries no trainer ids, build the headers" % IDS)
    return out


def by_class():
    """{class: [(constant, id, doubles)]} from the tree's own trainer data."""
    ids = trainer_ids()
    out = collections.defaultdict(list)
    for f in sorted(os.listdir(TRAINERS)):
        if not f.endswith(".json"):
            continue
        with open(os.path.join(TRAINERS, f)) as fh:
            j = json.load(fh)
        name = "TRAINER_" + f[:-len(".json")].upper()
        if name not in ids or not j.get("party"):
            continue
        out[j["class"]].append((name, ids[name], bool(j.get("double_battle"))))
    return out


def pick(entries):
    """The class's representative: the first single battle, else the first."""
    for e in entries:
        if not e[2]:
            return e
    return entries[0]


def run_one(sav, trainer_id, doubles):
    env = {k: v for k, v in os.environ.items() if not k.startswith("PC_")}
    # A doubles trainer fights as the same id twice, which is how
    # Encounter_NewVsTrainer selects BATTLE_TYPE_TRAINER_DOUBLES.
    spec = "trainer %d %d 0" % (trainer_id, trainer_id if doubles else 0)
    env.update({"PC_SAVE": sav, "PC_FRAMES": str(FRAMES), "PC_PACE": "0",
                "PC_INPUT": REPLAY, "PC_LAB_BATTLE": spec,
                "PC_LAB_BATTLE_AT": str(BATTLE_AT), "PC_TRACE_BATTLE": "1"})
    r = subprocess.run([BINARY], env=env, capture_output=True, text=True,
                       timeout=1800)
    err = r.stderr
    if "trainer AI dispatched opcode" in err:
        why = [l for l in err.split("\n") if "dispatched opcode" in l]
        return "trap", why[0]
    if r.returncode != 0:
        return "trap", "the port exited %d: %s" % (r.returncode, err[-300:].strip())
    if "pc_lab: starting battle" not in err:
        return "refused", "the battle never started"
    if "pc-battle:" not in err:
        return "refused", "the battle started and no HP line was produced in "\
                          "%d frames, so no turn was taken" % FRAMES
    return "clean", "%d HP event(s)" % err.count("pc-battle:")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--redo", default="",
                    help="re-measure rows with these outcomes, comma separated")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) - 2))
    args = ap.parse_args()

    os.makedirs(WORK, exist_ok=True)
    have = {}
    if os.path.exists(RESULTS):
        with open(RESULTS) as f:
            have = json.load(f)

    classes = by_class()
    if args.report:
        counts = collections.Counter(v["outcome"] for v in have.values())
        print("%d class(es) measured of %d: %s"
              % (len(have), len(classes), dict(counts)))
        for k, v in sorted(have.items()):
            if v["outcome"] != "clean":
                print("  %-40s %-8s %s" % (k, v["outcome"], v["why"]))
        return 0

    redo = {s for s in args.redo.split(",") if s}
    want = [c for c in sorted(classes)
            if c not in have or (redo and have[c]["outcome"] in redo)]
    if args.limit:
        want = want[:args.limit]
    print("%d class(es) to battle (%d already measured)" % (len(want), len(have)))

    sav_master = os.path.join(WORK, "ai.sav")
    recipe = os.path.join(WORK, "ai.recipe")
    with open(recipe, "w") as f:
        f.write(RECIPE)
    if not os.path.exists(sav_master):
        pc_lab.mint(recipe, sav_master)

    import concurrent.futures
    import shutil

    def one(cls):
        name, tid, doubles = pick(classes[cls])
        # A copy per battle: the port opens the save for writing and two
        # processes sharing one file would be measuring each other.
        sav = os.path.join(WORK, "%d.sav" % tid)
        shutil.copy(sav_master, sav)
        outcome, why = run_one(sav, tid, doubles)
        os.unlink(sav)
        return cls, {"trainer": name, "id": tid, "doubles": doubles,
                     "outcome": outcome, "why": why}

    done = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for cls, row in pool.map(one, want):
            have[cls] = row
            done += 1
            print("  %-42s %-8s %s" % (cls, row["outcome"], row["why"][:70]))
            with open(RESULTS, "w") as f:
                json.dump(have, f, indent=1, sort_keys=True)

    counts = collections.Counter(v["outcome"] for v in have.values())
    print("%d of %d class(es) measured: %s"
          % (len(have), len(classes), dict(counts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
