#!/usr/bin/env python3
"""
Transcribe linker-command-file symbols out of the ROM link's xMAP.

SDK_MAIN_ARENA_LO, the SDK_SECTION_ARENA_* trio, the stack sizes and the
digest bounds are linker-script symbols on hardware: no object defines them,
the linker command file does, and the SDK's C reads them as addresses/values
((u32)SDK_MAIN_ARENA_LO). The one honest source for their values is the ROM
link itself, build/rom/main.nef.xMAP lists every one on a
`#>ADDR  NAME (linker command file)` line. This script transcribes an
explicit list of names into absolute symbols for the PC link.

The list is explicit on purpose: the xMAP holds ~2000 SDK_* names (including
every SDK_OVERLAY_*_ID, which gen_overlay_map.py already owns), and emitting
all of them would both collide with that and make the link gate meaningless.

--define NAME=VALUE emits a symbol the xMAP does not have. The one current
use is SDK_OVERLAYTABLE_DIGEST: the ROM's own link never defines it (it is
digest-mode only, and the ROM does not enable digest mode) but this build
compiles every SDK C file, including the digest-mode ones the ROM leaves
out, so the reference exists here and not there. Zero is honest: the data
it would point at genuinely does not exist.

Usage: gen_lcf_syms.py main.nef.xMAP OUT.c NAME [NAME...] [--define N=V]
"""

import re
import sys

LINE_RE = re.compile(r"^#>([0-9A-Fa-f]{8})\s+(\S+)\s+\(linker command file\)")


def main():
    args = sys.argv[1:]
    defines = {}
    names = []
    it = iter(args)
    pos = []
    for a in it:
        if a == "--define":
            k, v = next(it).split("=", 1)
            defines[k] = int(v, 0)
        else:
            pos.append(a)
    if len(pos) < 3:
        sys.exit("usage: gen_lcf_syms.py main.nef.xMAP OUT.c NAME... [--define N=V]")
    xmap, out, names = pos[0], pos[1], pos[2:]

    found = {}
    with open(xmap, errors="replace") as fh:
        for line in fh:
            m = LINE_RE.match(line)
            if m and m.group(2) in names:
                found.setdefault(m.group(2), int(m.group(1), 16))

    missing = [n for n in names if n not in found and n not in defines]
    if missing:
        sys.exit("gen_lcf_syms: not in %s and not --define'd: %s"
                 % (xmap, " ".join(missing)))

    with open(out, "w") as fh:
        fh.write("/* generated by gen_lcf_syms.py from the ROM link's xMAP"
                 ", do not edit */\n")
        for n in names:
            v = found.get(n, defines.get(n))
            fh.write('__asm__(".global %s\\n\\t.set %s, %#x\\n");\n' % (n, n, v))
        for n, v in defines.items():
            if n not in names:
                fh.write('__asm__(".global %s\\n\\t.set %s, %#x\\n");\n'
                         % (n, n, v))


if __name__ == "__main__":
    main()
