#!/usr/bin/env python3
"""
Transcribe main.lsf's overlay membership into the flat table armrec reads.

This tree has no per-overlay directories: which overlay owns a source file is
recorded only in the linker spec, as an Object line inside the Nth Overlay
block. The ordinal is the block's position in the file, which is also the
value the SDK linker gives SDK_OVERLAY_<name>_ID, checked against
<buildname>/main.sha1, whose 130 lines list main.sbin and then one overlay
per line in the same order.

Output: one `stem ordinal` pair per line, stem being the Object path with the
.o stripped (src/field/fieldmap, asm/overlay_01_021E8744). Section
annotations like `Object foo.o (.wram)` lose the annotation; a stem listed in
two blocks is an error rather than a guess.

With --ids-out FILE it also writes a C file defining every
SDK_OVERLAY_<name>_ID as an absolute symbol with the block's ordinal as its
value. On hardware those are linker-script symbols; nothing else in this
build defines them, and both decompiled C (FS_OVERLAY_ID) and assembly
(`.public` via global.inc) refer to them by name.

Usage: gen_overlay_map.py [--ids-out FILE] main.lsf > build/pc/overlay-map.txt
"""

import re
import sys

BLOCK_RE = re.compile(r"^\s*(Static|Autoload|Overlay)\s+(\S+)")
OBJECT_RE = re.compile(r"^\s*Object\s+(\S+?)\.o\b")


def main():
    args = sys.argv[1:]
    ids_out = None
    if args and args[0] == "--ids-out":
        ids_out = args[1]
        args = args[2:]
    if len(args) != 1:
        sys.exit("usage: gen_overlay_map.py [--ids-out FILE] main.lsf")
    ordinal = -1
    in_overlay = False
    seen = {}
    names = []
    with open(args[0]) as fh:
        for line in fh:
            m = BLOCK_RE.match(line)
            if m:
                if m.group(1) == "Overlay":
                    ordinal += 1
                    in_overlay = True
                    name = m.group(2)
                    names.append(name)
                else:
                    in_overlay = False
                continue
            m = OBJECT_RE.match(line)
            if m and in_overlay:
                stem = m.group(1)
                if stem in seen and seen[stem][0] != ordinal:
                    sys.exit("gen_overlay_map: %s is in overlay %d (%s) and "
                             "%d (%s); membership must be unique"
                             % (stem, seen[stem][0], seen[stem][1],
                                ordinal, name))
                seen[stem] = (ordinal, name)
    for stem in sorted(seen):
        print("%s %d" % (stem, seen[stem][0]))
    if ids_out:
        with open(ids_out, "w") as fh:
            fh.write("/* generated by gen_overlay_map.py from main.lsf"
                     ", do not edit */\n")
            for i, name in enumerate(names):
                sym = "SDK_OVERLAY_%s_ID" % name
                fh.write('__asm__(".global %s\\n\\t.set %s, %d\\n");\n'
                         % (sym, sym, i))


if __name__ == "__main__":
    main()
