#!/usr/bin/env python3
"""
3ds/tests/mmap_pin.py: keep the shared-work shadow honest against the SDK.

3ds/include/3ds_hw_host.h redefines every constant that names an address in a
slab row the port resolves through a base pointer, so it lands in that row
rather than wherever the DS's arithmetic put it. The redefinitions are
mechanical, there are dozens of them, and a hand-maintained list that long is
one that will one day be missing a name, silently, because a constant that
keeps the SDK's value still compiles and still points somewhere.

So the list is derived here from the SDK headers, and this script fails if the
shadow's set of names is not exactly the derived one.

    3ds/tests/mmap_pin.py           verify
    3ds/tests/mmap_pin.py --emit    print the block to paste into the shadow

What counts as one. A constant is moved if its body resolves to an address
inside one of the rows in ROWS; either as `(HW_MAIN_MEM + 0x007fxxxx)`,
which is how the SDK writes the whole shared work area (an offset into an 8 MB
main memory this console does not have), or as an absolute literal. Sizes are
not addresses and are left alone. Constants built out of other constants
(HW_SHARED_LOCK_BUF is HW_VRAM_C_LOCK_BUF, HW_PLTT is HW_BG_PLTT) need
nothing: a macro expands at its use site, so once the one it is built from is
a host pointer, so is it.

Two names come from headers other than the one that owns their area:
HW_MAIN_MEM_EX_END (mmap_global.h) and HW_MAIN_MEM_SUB (mmap_main.h).

What must not move. Anything in 0x06000000-0x07000000. A VRAM window base
cannot be a host pointer: nine banks appear in five windows wherever VRAMCNT
puts them, the same 16 KB is at two addresses in two frames, and one base plus
an offset cannot express that. Those addresses stay as the DS writes them and
are translated per access. This script fails if one of them turns up in the
moved list.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SDK = os.path.join(ROOT, "subprojects", "NitroSDK-4.2.30001", "include", "nitro", "hw")
SHADOW = os.path.join(ROOT, "3ds", "include", "3ds_hw_host.h")

# name, guest base, guest end, and the macro in the shadow that resolves it.
# One row per base pointer the port keeps; a constant inside one is moved
# against that base. The shared work area is not contiguous with main RAM in
# this map even though the SDK's arithmetic says it is, which is why it needs a
# base of its own; see 3ds/include/3ds_hw_host.h.
ROWS = [
    ("SHARED", 0x027E0000, 0x02800000, "HWi_SHARED_HOST"),
    ("PALETTE", 0x05000000, 0x05001000, "HWi_PALETTE_HOST"),
    ("OAM", 0x07000000, 0x07001000, "HWi_OAM_HOST"),
]

# Nothing in here may be moved, whatever it looks like.
NEVER_LO = 0x06000000
NEVER_HI = 0x07000000

# HW_IOREG_END is 0x05000000, which is also where the palette row starts, so
# the range test claims it. It is not a palette address: it is the exclusive
# end of the I/O *address space*, and the register base was moved on its own
# terms. Leaving it alone keeps HW_IOREG and HW_IOREG_END a matched pair.
EXCLUDE = ["HW_IOREG_END"]

HEADERS = ["common/mmap_shared.h", "ARM9/mmap_global.h"]

DEFINE = re.compile(r"^#define\s+(HW_[A-Z0-9_]+)\s+(.*?)\s*$")
FROM_MAIN = re.compile(r"^\(\s*HW_MAIN_MEM\s*\+\s*(0x[0-9a-fA-F]+)\s*\)$")
ABSOLUTE = re.compile(r"^(0x[0-9a-fA-F]+)$")

# Named here rather than derived, because they are the two constants that
# describe this row from outside the header that owns it.
EXTRA = ["HW_MAIN_MEM_EX_END", "HW_MAIN_MEM_SUB"]

HW_MAIN_MEM = 0x02000000


def scan():
    """Every (name, address) the SDK writes as a plain address."""
    out = []
    for rel in HEADERS:
        with open(os.path.join(SDK, rel)) as fh:
            for line in fh:
                m = DEFINE.match(line)
                if not m:
                    continue
                name, body = m.group(1), m.group(2)
                g = FROM_MAIN.match(body)
                if g:
                    out.append((name, HW_MAIN_MEM + int(g.group(1), 16)))
                    continue
                g = ABSOLUTE.match(body)
                if g:
                    out.append((name, int(g.group(1), 16)))
    return out


def derive():
    """Ordered list of (name, address, row) for everything that moves."""
    out = []
    for name, addr in scan():
        if name in EXCLUDE:
            continue
        for row, lo, hi, _macro in ROWS:
            if lo <= addr <= hi:
                out.append((name, addr, row))
                break
    for name in EXTRA:
        out.append((name, None, "SHARED"))
    return out


def forbidden():
    """Names the shadow must never move."""
    return [n for n, a in scan() if NEVER_LO <= a < NEVER_HI]


BLOCK = re.compile(r"--- generated by .*?--emit.*?---(.*?)--- end generated ---", re.S)


def shadow_names():
    """The names inside the generated block, and only those. HW_MAIN_MEM is
    moved by hand outside it, after the capture, and is not this list's."""
    with open(SHADOW) as fh:
        text = fh.read()
    m = BLOCK.search(text)
    if not m:
        sys.exit("mmap_pin: no generated block in %s" % SHADOW)
    return re.findall(r"^#undef\s+(HW_[A-Z0-9_]+)\s*$", m.group(1), re.M)


def emit(rows):
    macro = dict((r[0], r[3]) for r in ROWS)
    end = dict((r[0], r[2]) for r in ROWS)
    print("/* Guest values, captured while the SDK's constants still say what a DS")
    print(" * says. This has to happen before anything is redefined: the shared")
    print(" * work area is written as an offset from HW_MAIN_MEM, which moves. */")
    for name, _addr, _row in rows:
        short = name[len("HW_"):]
        print("enum { HWi_G_%s = (int)(%s) };" % (short, name))
    print()
    for name, _addr, _row in rows:
        print("#undef %s" % name)
    print()
    for name, _addr, row in rows:
        short = name[len("HW_"):]
        print("#define %s %s(HWi_G_%s)" % (name, macro[row], short))
    print()
    print("/* Every one of them, for whatever wants to walk the set; which is")
    print(" * 3ds/src/3ds_hwmem.c, checking each against the translator. The end")
    print(" * of a row is passed so an exclusive bound can be checked at its last")
    print(" * byte: no translator can answer for a pointer one past a region. */")
    print("#define HWi_MOVED_EACH(X) \\")
    for i, (name, _addr, row) in enumerate(rows):
        short = name[len("HW_"):]
        tail = "" if i == len(rows) - 1 else " \\"
        print("    X(%s, %s, 0x%08Xu)%s" % (name, short, end[row], tail))


def main():
    rows = derive()
    if "--emit" in sys.argv[1:]:
        emit(rows)
        return 0

    want = [n for n, _a, _r in rows]
    got = shadow_names()
    missing = [n for n in want if n not in got]
    extra = [n for n in got if n not in want]
    moved_vram = [n for n in forbidden() if n in got]
    if moved_vram:
        print("mmap_pin: a VRAM window base cannot be a host pointer: %s"
              % " ".join(moved_vram))
        return 1
    if missing or extra:
        if missing:
            print("mmap_pin: the shadow does not move: %s" % " ".join(missing))
        if extra:
            print("mmap_pin: the shadow moves what the SDK does not put there: %s"
                  % " ".join(extra))
        return 1
    print("mmap_pin: %d constants moved, %d VRAM bases left alone, matches the SDK"
          % (len(want), len(forbidden())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
