#!/usr/bin/env python3
"""3ds/gen_absolutes.py: the link's constants, as constants.

A DS link expresses two kinds of number as an absolute *symbol*: the overlay
ordinals, where `FS_OVERLAY_ID(name)` takes the address of
`SDK_OVERLAY_<name>_ID` and the linker script made that address the ordinal;
and the memory-map values from the ROM's own script, where `HW_DTCM` is
`(u32)SDK_AUTOLOAD_DTCM_START`. The PC port reproduces both with `.set` in
generated C, and an ELF host does not mind.

A 3DSX does. It carries its own relocation table so the loader can place the
image, so every `R_ARM_ABS32` in it has to point at something inside code,
rodata or data. Neither an ordinal nor a DS address is, and `3dsxtool` refuses
the whole link over the first one it meets. So on this console the values stop
being symbols: this turns the same two generated files into a header of
constants, and the shadows and 3ds/patches use them.

Nothing is re-derived. The ordinals still come from main.lsf by way of
pc/gen_overlay_map.py and the addresses from the ROM's xMAP by way of
pc/gen_lcf_syms.py; this reads what those wrote.

    3ds/gen_absolutes.py build/pc/overlay_ids.c build/pc/lcf_syms.c OUT.h
"""

import os
import re
import sys

OVID = re.compile(r"\.set\s+SDK_OVERLAY_(\w+)_ID,\s*(\d+)")
LCF = re.compile(r"\.set\s+(SDK_\w+),\s*(0x[0-9a-fA-F]+|\d+)")


def read(path):
    try:
        return open(path).read()
    except OSError as e:
        sys.exit(f"gen_absolutes: {e}\n"
                 f"  run the PC pipeline first: it writes {path}")


def main(argv):
    if len(argv) != 4:
        sys.exit("usage: gen_absolutes.py overlay_ids.c lcf_syms.c OUT.h")

    ovsrc, lcfsrc, dst = argv[1], argv[2], argv[3]

    ids = OVID.findall(read(ovsrc))
    if not ids:
        sys.exit(f"gen_absolutes: no SDK_OVERLAY_*_ID in {ovsrc}")

    # The overlay ordinals are in the same file and are not memory-map values;
    # they are already covered above and must not appear twice.
    lcf = [(n, v) for n, v in LCF.findall(read(lcfsrc))
           if not n.endswith("_ID")]
    if not lcf:
        sys.exit(f"gen_absolutes: no SDK_* symbols in {lcfsrc}")

    out = ["/* generated by 3ds/gen_absolutes.py from %s and %s, do not edit */"
           % (os.path.basename(ovsrc), os.path.basename(lcfsrc)),
           "#ifndef POKEPLATINUM_3DS_ABSOLUTES_H",
           "#define POKEPLATINUM_3DS_ABSOLUTES_H",
           "",
           "/* Overlay ordinals; FS_OVERLAY_ID reads these on this console. */",
           "enum {"]
    out += [f"    SDK_OVID_{name} = {num}," for name, num in ids]
    out += ["};",
            "",
            "/* The ROM link's own values. GUEST addresses, every one: a user",
            " * translates before it dereferences. */"]
    out += [f"#define SDK_LCF_{name[len('SDK_'):]} {value}" for name, value in lcf]
    out += ["", "#endif", ""]

    body = "\n".join(out)
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    # Only write when it changed: this header is a prerequisite of every
    # object, and touching it would rebuild 1,433 of them.
    try:
        if open(dst).read() == body:
            print(f"  ABSOLUT {len(ids)} ordinals, {len(lcf)} link values (unchanged)")
            return 0
    except OSError:
        pass
    with open(dst, "w") as f:
        f.write(body)
    print(f"  ABSOLUT {len(ids)} ordinals, {len(lcf)} link values -> {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
