#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the Gen 4 character table (C source) from the decomp's charmap.

Input: games/platinum/tools/msgenc/charmap.txt (pret/pokeplatinum msgenc).
The file format and its parsing rules mirror MessagesConverter::ReadCharmap:
  HEXCODE=<utf-8 text>      a character (or multi-character token)
  HEXCODE={COMMAND}         a control command (follows a 0xFFFE escape)
  HEXCODE=\\n / \\r / \\f     newline / scroll / page break characters
`//` starts a comment; leading spaces/tabs are ignored, trailing are not.

Output defines (see ndsdata/src/gen4_text.c):
  g4_charmap[]      code -> UTF-8, sorted by code (decode)
  g4_charmap_enc[]  UTF-8 -> code, sorted by bytes; when several codes map to
                    the same text the one appearing last in the file wins,
                    exactly like msgenc's encoder (std::map overwrite).
  g4_cmdmap[]       command code -> name, sorted by code
  g4_strvar_hi[]    high bytes of STRVAR_* commands (code & 0xFF00)
"""
import sys


def c_str(b: bytes) -> str:
    out = []
    for ch in b:
        if ch == 0x22 or ch == 0x5C:
            out.append('\\' + chr(ch))
        elif 0x20 <= ch < 0x7F and ch != 0x3F:  # avoid trigraph '?'
            out.append(chr(ch))
        else:
            out.append('\\%03o' % ch)
    return '"' + ''.join(out) + '"'


def main() -> int:
    if len(sys.argv) != 3:
        print('usage: gen_charmap.py <charmap.txt> <out.c>', file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    chars = {}      # code -> bytes
    enc = {}        # bytes -> code (last wins)
    cmds = {}       # code -> name
    with open(src, 'rb') as f:
        raw = f.read().decode('utf-8')
    for lineno, line in enumerate(raw.splitlines(), 1):
        if '//' in line:
            line = line[:line.index('//')]
        line = line.lstrip(' \t')
        if not line:
            continue
        if '=' not in line:
            raise SystemExit('%s:%d: charmap syntax error' % (src, lineno))
        key, val = line.split('=', 1)
        code = int(key, 16)
        if len(val) >= 2 and val[0] == '{' and val[-1] == '}':
            cmds[code] = val[1:-1]
            continue
        if val.startswith('\\'):
            esc = {'\\n': '\n', '\\r': '\r', '\\f': '\f'}
            if val in esc:
                val = esc[val]
            elif val == '\\x0000':
                continue  # NUL placeholder, never part of real text
            else:
                raise SystemExit('%s:%d: bad escape %r' % (src, lineno, val))
        b = val.encode('utf-8')
        if not b:
            raise SystemExit('%s:%d: empty mapping' % (src, lineno))
        chars[code] = b
        enc[b] = code

    strvar_hi = sorted({c & 0xFF00 for c, n in cmds.items() if n.startswith('STRVAR_')})
    out = []
    out.append('/* Generated by features/tools/gen_charmap.py from %s. Do not edit. */' %
               src.replace('\\', '/').split('/games/')[-1])
    out.append('#include "gen4_charmap.h"')
    out.append('')
    out.append('const struct g4_char_entry g4_charmap[] = {')
    for code in sorted(chars):
        out.append('    {0x%04X, %s},' % (code, c_str(chars[code])))
    out.append('};')
    out.append('const size_t g4_charmap_count = sizeof(g4_charmap) / sizeof(g4_charmap[0]);')
    out.append('')
    out.append('const struct g4_char_entry g4_charmap_enc[] = {')
    for b in sorted(enc):
        out.append('    {0x%04X, %s},' % (enc[b], c_str(b)))
    out.append('};')
    out.append('const size_t g4_charmap_enc_count = sizeof(g4_charmap_enc) / sizeof(g4_charmap_enc[0]);')
    out.append('')
    out.append('const struct g4_char_entry g4_cmdmap[] = {')
    for code in sorted(cmds):
        out.append('    {0x%04X, %s},' % (code, c_str(cmds[code].encode('utf-8'))))
    out.append('};')
    out.append('const size_t g4_cmdmap_count = sizeof(g4_cmdmap) / sizeof(g4_cmdmap[0]);')
    out.append('')
    out.append('const uint16_t g4_strvar_hi[] = {%s};' % ', '.join('0x%04X' % v for v in strvar_hi))
    out.append('const size_t g4_strvar_hi_count = %d;' % len(strvar_hi))
    out.append('')
    with open(dst, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
