#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate Platinum event flag / variable name tables (C source).

Input: games/platinum/generated/vars_flags.txt (pret/pokeplatinum). The file
is consumed by the decomp's enumproc tool with C enum semantics: each line is
`NAME` (value = previous + 1) or `NAME = EXPR` where EXPR is an integer
literal or a previously defined NAME. Lines whose names do not start with
FLAG_ or VAR_ are range markers (e.g. HIDDEN_ITEM_FLAGS_START) and are not
emitted, but still participate in numbering exactly as an enum member would.

Output: save4_pt_flag_names[] / save4_pt_var_names[], each sorted by id.
"""
import re
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print('usage: gen_varsflags.py <vars_flags.txt> <out.c>', file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    values = {}
    order = []
    nxt = 0
    with open(src, encoding='utf-8') as f:
        for lineno, line in enumerate(f, 1):
            line = line.split('//')[0].split('#')[0].strip()
            if not line:
                continue
            m = re.fullmatch(r'([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*(\S+))?', line)
            if not m:
                raise SystemExit('%s:%d: cannot parse %r' % (src, lineno, line))
            name, expr = m.group(1), m.group(2)
            if expr is None:
                val = nxt
            elif re.fullmatch(r'0[xX][0-9a-fA-F]+|[0-9]+', expr):
                val = int(expr, 0)
            elif expr in values:
                val = values[expr]
            else:
                raise SystemExit('%s:%d: unknown symbol %r' % (src, lineno, expr))
            values[name] = val
            order.append(name)
            nxt = val + 1

    def table(prefix, cname):
        rows = sorted(((values[n], n) for n in order
                       if n.startswith(prefix) and not n.endswith(('_START', '_END'))),
                      key=lambda r: (r[0], r[1]))
        lines = ['const struct save4_named_id %s[] = {' % cname]
        lines += ['    {0x%04X, "%s"},' % (v, n) for v, n in rows]
        lines.append('};')
        lines.append('const size_t %s_count = sizeof(%s) / sizeof(%s[0]);' % (cname, cname, cname))
        return lines

    out = ['/* Generated by features/tools/gen_varsflags.py from games/platinum/generated/vars_flags.txt. Do not edit. */',
           '#include "save4/save4.h"', '']
    out += table('FLAG_', 'save4_pt_flag_names') + ['']
    out += table('VAR_', 'save4_pt_var_names') + ['']
    with open(dst, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
