#!/usr/bin/env python3
"""pc/wasm/gen_lcf_vars.py: the ROM link's values for a wasm build.

tools/armrec/gen_lcf_syms.py transcribes the linker-script symbols the SDK's
C reads (arena bounds, stack sizes, autoload bounds) out of the ROM's xMAP
as `.set` absolute symbols. A wasm object cannot express an absolute symbol,
so this turns that same file into:

  OUT.h  `#define SDK_X (*pc_lcf_SDK_X)` for every symbol, force-included
         into every translation unit by pc/wasm/include/pc_wasm_prelude.h;
  OUT.c  `void *pc_lcf_SDK_X = (void *)0x...;` the value itself.

Why a dereferenced pointer variable: the SDK declares these two ways,
`extern void SDK_X(void);` and `extern u32 SDK_X[];`, and uses them as
`(u32)SDK_X`, `((s32)SDK_X)` or `&SDK_X`. Under the macro the declarations
become `extern void (*pc_lcf_SDK_X)(void);` / `extern u32 (*pc_lcf_SDK_X)[];`,
both valid declarations of a pointer variable, and every use yields that
variable's value (a dereferenced function pointer or array pointer decays
straight back). The two TUs see different pointer types for one 4-byte
object; wasm-ld does not type data symbols and every pointer is an i32, so
that is a C-level formality, not a layout question. A static initializer
that needs one of these as a constant fails to compile and lands in the
skip count, loudly.

    gen_lcf_vars.py lcf_syms.c OUT.h OUT.c
"""

import os
import re
import sys

SET = re.compile(r"\.set\s+(SDK_\w+),\s*(0x[0-9a-fA-F]+|\d+)")


def write_if_changed(path, body):
    try:
        if open(path).read() == body:
            return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(body)


def main(argv):
    if len(argv) != 4:
        sys.exit("usage: gen_lcf_vars.py lcf_syms.c OUT.h OUT.c")
    src, out_h, out_c = argv[1:]
    syms = SET.findall(open(src).read())
    if not syms:
        sys.exit(f"gen_lcf_vars: no .set SDK_* symbols in {src}")

    h = ["/* generated by pc/wasm/gen_lcf_vars.py from %s, do not edit */"
         % os.path.basename(src),
         "#ifndef PC_WASM_LCF_H", "#define PC_WASM_LCF_H", ""]
    h += [f"#define {n} (*pc_lcf_{n})" for n, _ in syms]
    h += ["", "#endif", ""]

    c = ["/* generated by pc/wasm/gen_lcf_vars.py from %s, do not edit */"
         % os.path.basename(src), ""]
    c += [f"void *pc_lcf_{n} = (void *){v};" for n, v in syms]
    c += [""]

    write_if_changed(out_h, "\n".join(h))
    write_if_changed(out_c, "\n".join(c))
    print(f"  LCFVAR  {len(syms)} link values -> {os.path.basename(out_h)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
