/*
 * The window icon, for the SDL programs.
 *
 * On Windows the .ico in the exe's resource section is what Explorer and the
 * taskbar read, and SDL2 finds it on its own (it looks the resource up by the
 * name `SDL_icon` when it registers the window class). Everywhere else there
 * is no resource section, so the same picture is compiled in as pixels and
 * handed to SDL_SetWindowIcon. Calling it on Windows too is harmless; it is
 * the same artwork, and keeps one code path.
 *
 * pc_icon.h is generated by pc/gen_icon.py into the build directory.
 */
#ifndef PC_WINDOW_ICON_H
#define PC_WINDOW_ICON_H

#include <SDL.h>

#include "pc_icon.h"

static void pc_set_window_icon(SDL_Window *win)
{
    SDL_Surface *s;

    if (win == NULL) {
        return;
    }
    s = SDL_CreateRGBSurfaceWithFormatFrom((void *)pc_icon_rgba, PC_ICON_W,
                                           PC_ICON_H_PX, 32, PC_ICON_W * 4,
                                           SDL_PIXELFORMAT_RGBA32);
    if (s == NULL) {
        return;
    }
    SDL_SetWindowIcon(win, s);
    SDL_FreeSurface(s);
}

#endif
