#!/usr/bin/env python3
"""Emit gTrainerAITable as C, from the ROM build's own assembled bytecode.

The trainer AI is data, not ARM: src/battle/trainer_ai/script.s is an
offset-addressed bytecode program (every LabelDistance is a difference of
local labels, so the assembled bytes carry no addresses and no relocations
-- verified: `arm-none-eabi-objdump -r` lists none). The ROM build already
assembles it to build/rom/trainer_ai_script.o; this script lifts that
object's .text section into a `const u32 gTrainerAITable[]` the port links
where a zeroed stub used to sit.

The stub was's "zeroed until a guest-image loader
exists", and the first Pokémon battle anyone reached measured what a read
before then actually does: TrainerAI_EvalMoves dispatched an opcode out of
the zeroed table and died reading 0x20527020. This is the loader.

ELF parsing is done here in ~30 lines rather than through arm-none-eabi
binutils so the port build needs no ARM toolchain at all, build/rom is
already a hard prerequisite (lcf_syms comes from its xMAP).
"""

import struct
import sys


def elf_section(path, want):
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\x7fELF" or data[4] != 1 or data[5] != 1:
        raise SystemExit("%s: not a 32-bit little-endian ELF" % path)
    e_shoff, = struct.unpack_from("<I", data, 0x20)
    e_shentsize, e_shnum, e_shstrndx = struct.unpack_from("<HHH", data, 0x2E)

    def sh(i):
        off = e_shoff + i * e_shentsize
        name, _, _, _, offset, size = struct.unpack_from("<6I", data, off)
        return name, offset, size

    _, stroff, _ = sh(e_shstrndx)
    for i in range(e_shnum):
        name, offset, size = sh(i)
        end = data.index(b"\0", stroff + name)
        if data[stroff + name:end].decode() == want:
            return data[offset:offset + size]
    raise SystemExit("%s: no %s section" % (path, want))


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_trainer_ai.py <trainer_ai_script.o> <out.c>")
    text = elf_section(sys.argv[1], ".text")
    if len(text) % 4:
        text += b"\0" * (4 - len(text) % 4)
    words = struct.unpack("<%dI" % (len(text) // 4), text)

    with open(sys.argv[2], "w") as out:
        out.write("/* generated by pc/gen_trainer_ai.py from the ROM build's"
                  " trainer_ai_script.o, do not edit */\n")
        out.write("typedef unsigned int u32;\n")
        out.write("const u32 gTrainerAITable[%d] = {\n" % len(words))
        for i in range(0, len(words), 6):
            out.write("    " + ", ".join("0x%08x" % w
                                         for w in words[i:i + 6]) + ",\n")
        out.write("};\n")
    print("  TRAI    gTrainerAITable: %d bytes of AI bytecode" % len(text))


if __name__ == "__main__":
    main()
